In [1]:
import numpy
from pyscf import lib
from pyscf import gto
from pyscf import gto, scf
mol = gto.M(atom='H 0 0 0; H 0 0 1.1')
dms = numpy.random.random((mol.nao_nr(),mol.nao_nr()))
dms

array([[0.70375769, 0.79173595],
       [0.10458461, 0.65677868]])

In [2]:
# call scf 
j, k = scf.hf.get_jk(mol, dms, hermi=0)
print(j)
print(k)

[[1.0765465  0.46947095]
 [0.46947095 1.06114187]]
[[0.86242096 0.72759578]
 [0.50356803 0.83170004]]


In [3]:
mol.intor('int2e_sph')
print(numpy.einsum('ijkl,kl->ij',mol.intor('int2e_sph'),dms ))
print(numpy.einsum('ijkl,jl->ik',mol.intor('int2e_sph'),dms ))

[[1.0765465  0.46947095]
 [0.46947095 1.06114187]]
[[0.86242096 0.72759578]
 [0.50356803 0.83170004]]


In [4]:
mol.intor('int2e_sph')

array([[[[0.77460594, 0.26556095],
         [0.26556095, 0.44670128]],

        [[0.26556095, 0.12067738],
         [0.12067738, 0.26556095]]],


       [[[0.26556095, 0.12067738],
         [0.12067738, 0.26556095]],

        [[0.44670128, 0.26556095],
         [0.26556095, 0.77460594]]]])