In [68]:
import numpy
from pyscf import lib
from pyscf import gto
from pyscf import gto, scf
mol = gto.M(atom='H 0 0 0; H 0 0 1.1',basis="sto-3g")
dms = numpy.random.random((mol.nao_nr(),mol.nao_nr()))
dms

array([[0.95651279, 0.71477176],
       [0.86597298, 0.36325793]])

In [75]:
# call scf 
J,K = scf.hf.get_jk(mol, dms, hermi=0)
print(J)
print(K)

[[1.32297234 0.5412397 ]
 [0.5412397  1.12844131]]
[[1.20454158 0.77427237]
 [0.82356758 0.81659528]]


In [70]:
g_ijkl=mol.intor('int2e_sph')
print(numpy.einsum('ijkl,kl->ij',mol.intor('int2e_sph'),dms ))
print(numpy.einsum('ijkl,jl->ik',mol.intor('int2e_sph'),dms ))

[[1.32297234 0.5412397 ]
 [0.5412397  1.12844131]]
[[1.20454158 0.77427237]
 [0.82356758 0.81659528]]


In [71]:
g_ijkl

array([[[[0.77460594, 0.26556095],
         [0.26556095, 0.44670128]],

        [[0.26556095, 0.12067738],
         [0.12067738, 0.26556095]]],


       [[[0.26556095, 0.12067738],
         [0.12067738, 0.26556095]],

        [[0.44670128, 0.26556095],
         [0.26556095, 0.77460594]]]])

In [72]:
g2=numpy.swapaxes(g_ijkl,1,2)
g2

array([[[[0.77460594, 0.26556095],
         [0.26556095, 0.12067738]],

        [[0.26556095, 0.44670128],
         [0.12067738, 0.26556095]]],


       [[[0.26556095, 0.12067738],
         [0.44670128, 0.26556095]],

        [[0.12067738, 0.26556095],
         [0.26556095, 0.77460594]]]])

In [73]:
nao=2
for i in range(nao):
    for j in range(nao):
        for k in range(nao):
            for l in range(nao):
                if not (numpy.allclose(g2[i][k][j][l],g_ijkl[i][j][k][l])):
                    print("not")

In [76]:
print (K)

[[1.20454158 0.77427237]
 [0.82356758 0.81659528]]


In [77]:
numpy.einsum('ijkl,kl->ij',g2,dms )

array([[1.20454158, 0.77427237],
       [0.82356758, 0.81659528]])

In [78]:
print (J-K/2)

[[0.72070155 0.15410351]
 [0.12945591 0.72014367]]


In [79]:
numpy.einsum('ijkl,kl->ij',g_ijkl-g2/2,dms )

array([[0.72070155, 0.15410351],
       [0.12945591, 0.72014367]])

In [51]:
co=gto.Mole(atom="C 0 0 0 ;O 0 0 2.1", basis= "sto-3G",units="Bohr")
co.build()
g_ijkl=co.intor('int2e_sph')

<class 'pyscf.gto.mole.Mole'> does not have attributes  units


In [54]:
nao=co.nao
for i in range(nao):
    for j in range(nao):
        for k in range(nao):
            for l in range(nao):
                if not (numpy.allclose(g_ijkl[i][j][k][l],g_ijkl[i][j][k][l])):
                    print("not")