In [1]:
from pyscf import scf,gto
import numpy as np
import inspect
from FcMole import FcM
import matplotlib.pyplot as plt
from pyscf.grad import rhf as grhf  #### very important
from pyscf.hessian import rhf as hrhf # without those two mf.Gradients() and mf.Hessian() don't work
def DeltaV(mol,dL):
    mol.set_rinv_orig_(mol.atom_coords()[0])
    dV=mol.intor('int1e_rinv')*dL[0]
    mol.set_rinv_orig_(mol.atom_coords()[1])
    dV+=mol.intor('int1e_rinv')*dL[1]
    return -dV

First compare gradient analytical from fcm with the one via finite differences on geometry


In [2]:
mol1=FcM(fcs=[.001,-.001],atom="C 0 0 0; O 0 0 1.8",unit="Bohr",basis="STO-3G")
mf1=scf.RHF(mol1)
mf1.scf(dm0=mf1.init_guess_by_1e(mol1))
g1=mf1.Gradients()
g1.run()

converged SCF energy = -111.05722603438
--------------- RHF gradients ---------------
         x                y                z
0 C    -0.0000000000     0.0000000000     1.0869705326
1 O     0.0000000000    -0.0000000000    -1.0869705326
----------------------------------------------


In [3]:
mol0=gto.M(atom="C 0 0 0; O 0 0 1.8",unit="Bohr",basis="STO-3G")
mf0=scf.RHF(mol0)
mf0.scf()
g0=mf0.Gradients()
g0.kernel()

converged SCF energy = -111.064463936466
--------------- RHF gradients ---------------
         x                y                z
0 C    -0.0000000000     0.0000000000     1.0871732099
1 O     0.0000000000    -0.0000000000    -1.0871732099
----------------------------------------------


array([[-1.27318183e-16,  4.87683781e-16,  1.08717321e+00],
       [ 1.27318183e-16, -4.87683781e-16, -1.08717321e+00]])

In [4]:
from alch_deriv import alch_deriv

The formula for the gradient is stated in Pople's article (Eq.21) as: 
$$ \frac{\partial E}{\partial x}= \sum_{\mu\nu}P_{\mu\nu}\frac{\partial H_{\mu\nu}}{\partial x}+\frac{1}{2}\sum_{\mu\nu\lambda\sigma}
P_{\mu\nu}P_{\lambda\sigma}\frac{\partial}{\partial x}(\mu \lambda | | \nu\sigma)+\frac{\partial V_{nuc}}{\partial x} 
-\sum_{\mu\nu}W_{\mu\nu}\frac{\partial S_{\mu\nu}}{\partial x}
$$
$W$ is an energy weighted density matrix:
$$ W_{\mu\nu}= \sum_i ^{mo.occ.} c_{\mu i} \epsilon_i    c_{\nu i}^\dagger = S^{-1}FCOC^\dagger=S^{-1}FP
$$

In [5]:
(U,dP)=alch_deriv(mf0,dL=[[0,1],[-1,1]])
P=mf0.make_rdm1()
P1=mf1.make_rdm1()

[[0, 1], [-1, 1]]


First piece:
$$\sum_{\mu\nu}P_{\mu\nu}\frac{\partial H_{\mu\nu}}{\partial x}$$

$\frac{\partial H^{(1)}}{\partial x }$ is to be update to the new fract charges

In [6]:
comp1=np.zeros((2,3,10,10))
comp1[0]=g1.hcore_generator()(0)-g0.hcore_generator()(0)
comp1[1]=g1.hcore_generator()(1)-g0.hcore_generator()(1)

In [7]:
comp2=np.zeros((2,3,10,10))
dL=[.001,-.001]
for atm_id in [0,1]:
    with mol0.with_rinv_at_nucleus(atm_id):
        vrinv = -mol0.intor('int1e_iprinv', comp=3)
    shl0, shl1, p0, p1 = mol0.aoslice_by_atom()[atm_id]
    vrinv*=dL[atm_id]
    vrinv[:,p0:p1] += (g1.get_hcore()-g0.get_hcore())[:,p0:p1]
    vrinv += vrinv.transpose(0,2,1)
    comp2[atm_id]=vrinv

In [8]:
np.allclose(comp1,comp2)   #the difference lyes in  g.get_hcore()

True

g0.get_hcore() is the integral $<\chi_\mu |\nabla_r \hat{H}^{(1)}|\chi_\nu> $ is composed by two parts: the first refered to the kintic energy operator which is alchemy invariant, the second which has to be computed is refered to the nuclear electron attraction. <br>
To compute this we use moleintor.getints() using as arguments a mol environment (mol._env) with the added fractional charges and a mol._atm desription that show fractional charges.
Not forget to put a minus sign !!!! 

In [9]:
NUC_FRAC_CHARGE=gto.mole.NUC_FRAC_CHARGE
NUC_MOD_OF=gto.mole.NUC_MOD_OF
PTR_FRAC_CHARGE=gto.mole.PTR_FRAC_CHARGE
denv=mol0._env.copy()
datm=mol0._atm.copy()
fcs=[.001,-.001]
datm[:,NUC_MOD_OF] = NUC_FRAC_CHARGE
for i in range (mol0.natm):
    denv[datm[i,PTR_FRAC_CHARGE]]=fcs[i] 
dH1=-gto.moleintor.getints('int1e_ipnuc_sph',datm,mol0._bas,denv, None,3,0,'s1')   #minus sign !

In [10]:
comp2=np.zeros((2,3,10,10))
dL=[.001,-.001]
for atm_id in [0,1]:
    with mol0.with_rinv_at_nucleus(atm_id):
        vrinv = -mol0.intor('int1e_iprinv', comp=3)
    shl0, shl1, p0, p1 = mol0.aoslice_by_atom()[atm_id]
    vrinv*=dL[atm_id]
    vrinv[:,p0:p1] += dH1[:,p0:p1]  #bearbeiten
    vrinv += vrinv.transpose(0,2,1)
    comp2[atm_id]=vrinv
np.allclose(comp1,comp2)

True

In [11]:
fdg=np.zeros((2,3))   #finite difference part 1 gradient
fdg[0]+=np.einsum('xij,ij->x', g1.hcore_generator()(0),mf1.make_rdm1())
fdg[0]-=np.einsum('xij,ij->x', g0.hcore_generator()(0),mf0.make_rdm1())
fdg[1]+=np.einsum('xij,ij->x', g1.hcore_generator()(1),mf1.make_rdm1())
fdg[1]-=np.einsum('xij,ij->x', g0.hcore_generator()(1),mf0.make_rdm1())
fdg

array([[ 7.59029234e-16, -1.60896510e-14, -5.24349964e-03],
       [-7.59029234e-16,  1.60896510e-14,  5.24349964e-03]])

In [12]:
ga_1=np.zeros((2,3))     # analytical gradient _part 1 
ga_1[0]+=np.einsum('xij,ij->x', g0.hcore_generator()(0),dP)
ga_1[1]+=np.einsum('xij,ij->x', g0.hcore_generator()(1),dP)
#print(ga_1)
ga_1[0]+=np.einsum('xij,ij->x', comp2[0],P)
ga_1[1]+=np.einsum('xij,ij->x', comp2[1],P)
print(ga_1)

[[ 2.00402879e-15 -4.04907388e-15  4.42753694e+00]
 [-2.00402879e-15  4.04907388e-15 -4.42753694e+00]]


# Second piece:
$$\frac{\partial}{\partial Z} (P_{\mu\nu}P_{\lambda\sigma}\frac{\partial}{\partial x}(\mu \lambda | | \nu\sigma) )$$
here the two electron integral is invariant to alchemy, therefore is sufficient insert the density matrix derivative $dP$ in the following exression. 

In [13]:
#for the ref molecule
aoslices = mol0.aoslice_by_atom()
g2e_part2_0=np.zeros((2,3))
for ia in [0,1]:
    p0, p1 = aoslices [ia,2:]
    vhf = g0.get_veff(mol0, P)
    g2e_part2_0[ia]=(np.einsum('xij,ij->x', vhf[:,p0:p1], P[p0:p1]) * 2)        #   P (Pd/dx(ml||ns))
g2e_part2_0    

array([[ 6.20787738e-15, -2.73985264e-14,  1.17925050e+01],
       [-6.20787738e-15,  2.73985264e-14, -1.17925050e+01]])

In [14]:
aoslices = mol1.aoslice_by_atom()
g2e_part2_1=np.zeros((2,3))
for ia in [0,1]:
    p0, p1 = aoslices [ia,2:]
    vhf = g1.get_veff(mol1, P1)
    g2e_part2_1[ia]=(np.einsum('xij,ij->x', vhf[:,p0:p1], P1[p0:p1]) * 2) 
g2e_part2_1

array([[ 5.61803875e-15, -1.26309668e-14,  1.17969070e+01],
       [-5.61803875e-15,  1.26309668e-14, -1.17969070e+01]])

In [15]:
#check the invariance:
np.allclose(g0.get_veff(mol0, P),g1.get_veff(mol1, P1))

False

In [16]:
print(np.allclose(g0.get_veff(mol0, P1),g1.get_veff(mol1, P1))) #update P
print(np.allclose(g0.get_veff(mol0, P+dP),g1.get_veff(mol1, P1))) #update P

True
False


In [17]:
aoslices = mol0.aoslice_by_atom()
ga_2=np.zeros((2,3))
for ia in [0,1]:
    p0, p1 = aoslices [ia,2:]
    vhf = g0.get_veff(mol0, P)
    vhf_1 = g0.get_veff(mol0, P+dP)
    ga_2[ia]=(np.einsum('xij,ij->x', vhf[:,p0:p1], dP[p0:p1]) * 2)
    ga_2[ia]+=(np.einsum('xij,ij->x',vhf_1[:,p0:p1]-vhf[:,p0:p1], P[p0:p1]) * 2)
ga_2

array([[-1.60702648e-15,  4.46525151e-15, -4.40679234e+00],
       [ 1.60702648e-15, -4.46525151e-15,  4.40679234e+00]])

In [18]:
np.allclose(ga_2,g2e_part2_1-g2e_part2_0,atol=1e-3)

False

In [19]:
g2e_part2_1-g2e_part2_0

array([[-5.89838634e-16,  1.47675596e-14,  4.40195061e-03],
       [ 5.89838634e-16, -1.47675596e-14, -4.40195061e-03]])

# Third piece:
$$-\sum_{\mu\nu}W_{\mu\nu}\frac{\partial S_{\mu\nu}}{\partial x}
$$
Luckily $S$ is invariant in alchemy, therefore the different in gradient is just:$$
-\sum_{\mu\nu}\frac{\partial W_{\mu\nu}}{\partial Z}\frac{\partial S_{\mu\nu}}{\partial x}
$$
### Obtaining derivatives of W
$$W=  \sum_i ^{mo.occ.} \epsilon_i C_{\mu i} C_{\nu i}^\dagger 
$$

$$ \frac{\partial W}{\partial Z_I}= \sum_i ^{mo.occ.} \left( \epsilon_i (CU)_{\mu i} C_{\nu i}^\dagger + 
\epsilon_i C_{\mu i} (CU)^\dagger_{\nu i}   +\frac{\partial \epsilon_i}{\partial Z_I} C_{\mu i} C_{\nu i}^\dagger \right)$$


$$ S W= S C\epsilon C^\dagger=FCC^\dagger= FP $$
$$W=  S^{-1}FP $$

In [20]:
"""  THE CODE IN g.grad_elec()
dme0 = mf_grad.make_rdm1e(mo_energy, mo_coeff, mo_occ)        W
s1 = mf_grad.get_ovlp(mol)%autocall                         dS/dx
for k, ia in enumerate(atmlst):
    de[k] -= numpy.einsum('xij,ij->x', s1[:,p0:p1], dme0[p0:p1]) * 2        W dS/dx
"""
pass

In [21]:
#verify that s1 is invariant
s1=g0.get_ovlp(mol0)
np.allclose(g0.get_ovlp(mol0),g1.get_ovlp(mol1))

True

In [22]:
#at first by finite differences 
W1=g1.make_rdm1e()
W0=g0.make_rdm1e()
fd_dW=W1-W0

In [23]:
# W0 can be constructed via C@np.diag(o*e)@C.T
o=mf0.mo_occ
O=np.diag(o)
e=mf0.mo_energy
C=mf0.mo_coeff
S=mf0.get_ovlp()
F=mf0.get_fock()
np.allclose(C@np.diag(e*o)@C.T,W0)

True

In [24]:
#to derive this expression first get dC as 
dC=C@U
#to get d(e) we need to get the fock hamiltonian and than get the new eigenvalues 
g_ijkl=mol0.intor('int2e_sph')
dF2el=np.einsum('ijkl,kl->ij',g_ijkl,dP)-0.5*np.einsum('ijkl,jl->ik',g_ijkl,dP)
dV=DeltaV(mol0,[.001,-.001])

In [25]:
np.allclose(mf1.get_fock()-F,dV+dF2el,atol=1e-5)

False

In [26]:
#try to get e in another way , using Roothans equations FC=SCe
print(np.allclose(np.linalg.inv(S)@F@(C),C@np.diag(e))) # S^-1 F C= C e 
print(np.allclose(np.linalg.inv(S)@F@P,W0))  #S^-1 F (C O C.T) = S^-1 F P = C e O C.T =W !!!!

True
True


In [27]:
dW_a3=np.linalg.inv(S)@(F+dV+dF2el)@(P+dP)-W0
np.max(fd_dW-dW_a3)

1.7934526535627664

In [28]:
W1_contr=np.zeros((2,3))
ga_3=np.zeros((2,3))
W0_contr=np.zeros((2,3))
for ia in [0,1]:
    p0, p1 = mol0.aoslice_by_atom() [ia,2:]
    W1_contr[ia] -= np.einsum('xij,ij->x', s1[:,p0:p1], W1[p0:p1]) * 2
    ga_3[ia] -= np.einsum('xij,ij->x', s1[:,p0:p1], dW_a3[p0:p1]) * 2
    W0_contr[ia] -= np.einsum('xij,ij->x', s1[:,p0:p1], W0[p0:p1]) * 2
(ga_3),W1_contr-W0_contr

(array([[-1.71722452e-15,  4.77857332e-16,  2.88829462e+00],
        [ 1.69574284e-15, -9.91737117e-15,  3.27604798e+00]]),
 array([[-3.24106850e-16,  9.50489581e-16,  2.18963806e-05],
        [ 3.24106850e-16, -9.50489581e-16, -2.18963806e-05]]))

In [29]:
#W=S^-1F P is the way, cause of the orbital rotation
S=mf0.get_ovlp()
F=mf0.get_fock()
g_ijkl=mol0.intor('int2e_sph')
dF2el=np.einsum('ijkl,kl->ij',g_ijkl,dP)-0.5*np.einsum('ijkl,jl->ik',g_ijkl,dP)
dV=DeltaV(mol0,[.001,-.001])
dW_a3=np.linalg.inv(S)@(F+dV+dF2el)@(P+dP)-W0

In [30]:
ga_1+ga_2+ga_3  

array([[-1.32022221e-15,  8.94034965e-16,  2.90903921e+00],
       [ 1.29874053e-15, -1.03335488e-14,  3.25530338e+00]])

In [31]:
g1.grad_elec()-g0.grad_elec()

array([[-1.54916250e-16, -3.71601804e-16, -8.19652647e-04],
       [ 1.54916250e-16,  3.71601804e-16,  8.19652647e-04]])

## At the end the nuclear nuclear part 

In [32]:
"""def grad_nuc(mol, atmlst=None):
    gs = numpy.zeros((mol.natm,3))
    for j in range(mol.natm):
        q2 = mol.atom_charge(j)      <----------------------- derive here
        r2 = mol.atom_coord(j)
        for i in range(mol.natm):
            if i != j:
                q1 = mol.atom_charge(i)     <----------------------- and here 
                r1 = mol.atom_coord(i)      
                r = numpy.sqrt(numpy.dot(r1-r2,r1-r2))
                gs[j] -= q1 * q2 * (r2-r1) / r**3
    if atmlst is not None:
        gs = gs[atmlst]
    return gs
    """
pass

In [33]:
#is now easy to derive this function with respect to the nuclear charges
def alc_deriv_grad_nuc(mol,dL, atmlst=None):
    gs = np.zeros((mol.natm,3))
    for j in range(mol.natm):
        q2 =  mol.atom_charge(j) + dL[j]
        r2 = mol.atom_coord(j) 
        for i in range(mol.natm):
            if i != j:
                q1 = mol.atom_charge(i) +dL[i]
                r1 = mol.atom_coord(i)
                r = np.sqrt(np.dot(r1-r2,r1-r2))
                gs[j] -= q1 * q2 * (r2-r1) / r**3
    if atmlst is not None:
        gs = gs[atmlst]
    return gs

In [34]:
ga_4=alc_deriv_grad_nuc(mol0,[.001,-.001])-g0.grad_nuc()
ga_4

array([[ 0.        ,  0.        ,  0.00061698],
       [ 0.        ,  0.        , -0.00061698]])

In [35]:
g1.grad_nuc()-g0.grad_nuc()

array([[ 0.        ,  0.        ,  0.00061698],
       [ 0.        ,  0.        , -0.00061698]])

In [36]:
g0.grad_nuc()

array([[  0.        ,   0.        ,  14.81481481],
       [  0.        ,   0.        , -14.81481481]])

## Final comparison 

In [37]:
ga_1+ga_2+ga_3+ga_4

array([[-1.32022221e-15,  8.94034965e-16,  2.90965619e+00],
       [ 1.29874053e-15, -1.03335488e-14,  3.25468641e+00]])

In [38]:
gfd=g1.grad()-g0.grad()

--------------- RHF gradients ---------------
         x                y                z
0 C    -0.0000000000     0.0000000000     1.0869705326
1 O     0.0000000000    -0.0000000000    -1.0869705326
----------------------------------------------
--------------- RHF gradients ---------------
         x                y                z
0 C    -0.0000000000     0.0000000000     1.0871732099
1 O     0.0000000000    -0.0000000000    -1.0871732099
----------------------------------------------


In [41]:
mol_nn=FcM(fcs=[1,-1],atom="C 0 0 0; O 0 0 2.05",unit="Bohr",basis="STO-3G")
mf_nn=scf.RHF(mol_nn)
mf_nn.scf(dm0=mf_nn.init_guess_by_1e())
g_nn=mf_nn.Gradients()
g_nn.run()

converged SCF energy = -105.439066087168
--------------- RHF gradients ---------------
         x                y                z
0 C    -0.0000000000     0.0000000000     0.1755432988
1 O     0.0000000000    -0.0000000000    -0.1755432988
----------------------------------------------


In [44]:
mol_bf=FcM(fcs=[-1,1],atom="C 0 0 0; O 0 0 2.05",unit="Bohr",basis="STO-3G")
mf_bf=scf.RHF(mol_bf)
mf_bf.scf(dm0=mf_bf.init_guess_by_1e())
g_bf=mf_bf.Gradients()
g_bf.run()

converged SCF energy = -119.891952783638
--------------- RHF gradients ---------------
         x                y                z
0 C    -0.0000000000    -0.0000000000     0.5777073343
1 O     0.0000000000     0.0000000000    -0.5777073343
----------------------------------------------


In [45]:
mol_bf=FcM(fcs=[0,0],atom="C 0 0 0; O 0 0 2.05",unit="Bohr",basis="STO-3G")
mf_bf=scf.RHF(mol_bf)
mf_bf.scf(dm0=mf_bf.init_guess_by_1e())
g_bf=mf_bf.Gradients()
g_bf.run()

converged SCF energy = -111.21367962675
--------------- RHF gradients ---------------
         x                y                z
0 C     0.0000000000     0.0000000000     0.2188666669
1 O    -0.0000000000    -0.0000000000    -0.2188666669
----------------------------------------------
