In [ ]:
import numpy as np
import glob
from matplotlib import pyplot as plt

import sys
sys.path.insert(0, '/home/misa/git_repositories/APDFT/prototyping/atomic_energies')
import alchemy_tools2 as at

from parse_density_files import CUBE

In [ ]:
#'/home/misa/projects/Atomic-Energies/data/dsgdb9nsd_003664/cube-files'
#'/home/misa/projects/Atomic-Energies/data/dsgdb9nsd_003700/cube-files'


#'/home/misa/APDFT/prototyping/atomic_energies/results/slice_ve38/dsgdb9nsd_003886'
#'/home/misa/projects/Atomic-Energies/data/dsgdb9nsd_003712/cube-files'



In [ ]:
files = glob.glob('/home/misa/APDFT/prototyping/atomic_energies/results/slice_ve38/dsgdb9nsd_001212/cube-files/*')
files.sort()
files.remove('/home/misa/APDFT/prototyping/atomic_energies/results/slice_ve38/dsgdb9nsd_001212/cube-files/ve_8.cube')
files

In [ ]:
lam_vals, density, nuclei, gpts, h_matrix = at.load_cube_data(files)

In [ ]:
alchpots_all = []
for d in density:
    atomic_energies_with_repulsion, atomic_energies, alch_pots = at.calculate_atomic_energies(d, nuclei, gpts, h_matrix, intg_method = 'sum')
    alchpots_all.append(alch_pots)
alchpots_all = np.array(alchpots_all)
np.save('/home/misa/projects/Atomic-Energies/data/ueg_reference/alchpots/dsgdb9nsd_003712_alchpots.npy', alchpots_all)

In [ ]:
plt.rcParams['font.size'] = 20
for i in range(alchpots_all.shape[1]):
    plt.plot(lam_vals, alchpots_all[:,i], '-o', label = f'Z = {nuclei[:,0][i]}')

plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\mu (\lambda)$ (Ha)')

plt.legend(bbox_to_anchor=(1.05, 1))

In [ ]:
plt.plot(lam_vals, alchpots_all[:,3], '-o')

In [ ]:
coeffs = np.polyfit(lam_vals, alchpots_all[:,3], 3, rcond=None, full=False, w=None, cov=False)
coeffs2 = np.polyfit(lam_vals[[2,6,11,15, -1]], alchpots_all[:,3][[2,6,11,15, -1]], 3, rcond=None, full=False, w=None, cov=False)

In [ ]:
plt.plot(lam_vals, alchpots_all[:,3], '-o')
plt.plot(np.linspace(0, 1, 100), np.polyval(coeffs, np.linspace(0, 1, 100)))
plt.plot(np.linspace(0, 1, 100), np.polyval(coeffs2, np.linspace(0, 1, 100)))

In [ ]:
poly1 = np.poly1d(coeffs)

### Integral of alchemical potentials

In [14]:
import numpy as np
import glob
from matplotlib import pyplot as plt

import sys
sys.path.insert(0, '/home/misa/git_repositories/APDFT/prototyping/atomic_energies')

In [15]:
alchpots = np.load('/home/misa/projects/Atomic-Energies/data/ueg_reference/alchpots/dsgdb9nsd_001212_alchpots.npy')

In [16]:
alchpots_lam1 = np.loadtxt('/home/misa/APDFT/prototyping/atomic_energies/results/slice_ve38/dsgdb9nsd_001212/alchpot_lam1.txt')

In [4]:
lam = np.array([ 0.,  4.,  6.,  8., 10., 12., 14., 15., 16., 18., 20., 22., 23.,
       24., 26., 28., 29., 30., 32., 34., 36., 38.])

lam_coarse = lam[[0, 3, 7, 12, 17, -1]]/38

In [23]:
alch_tilde = []
for i in range(alchpots[[0, 3, 7, 12, 17, -1]].shape[1]):
    alch_tilde.append(np.trapz(alchpots[[0, 3, 7, 12, 17, -1]][:,i], lam_coarse))

In [20]:
mean = alchpots[0].mean()
alchpots[0] = mean

In [25]:
alch_tilde-atomic_data[:,4]

array([-7.13228434e-05, -1.29789771e-03, -5.01491929e-04, -1.62481098e-03,
       -5.39916104e-04,  6.43125371e-04,  1.49678645e-03,  9.59557677e-04,
        4.39201606e-04,  3.85541857e-04,  5.15724906e-05,  5.96541185e-05])

In [8]:
atomic_data = np.loadtxt('/home/misa/APDFT/prototyping/atomic_energies/results/slice_ve38/dsgdb9nsd_001212/atomic_energies_with_mic.txt')

In [11]:
atomic_data[:,4]

array([-6.20622947, -7.32980863, -7.23264147, -7.85531781, -6.91388678,
       -6.41388426, -5.93576637, -5.27404281, -5.39576267, -5.39437558,
       -5.91036065, -5.91095847])

In [27]:
alchpots_lam1[:,4]

array([-10.51306256, -12.69052216, -13.48896537, -14.69440176,
       -11.87340373, -10.94058547, -10.3957795 ,  -8.24772397,
        -8.47002033,  -8.46562752,  -9.52475082,  -9.52861404])