In [1]:
import sys
sys.path.append("/home/administrator/Documenti/APDFT/prototyping/hessian/AAFF/Libs/")
from ABSE import absec
from aaff import aaff,alc_deriv_grad_nuc,alc_differential_grad_nuc
from FcMole import FcM
from alch_deriv import alch_deriv
from pyscf import gto,scf
import numpy as np 
from numpy.linalg import norm as norm
import basis_set_exchange as bse
from FDcoeffs import *
from pyscf.geomopt.berny_solver import optimize
ang2bohr=1.8897261246
bohr2ang=.5291772109
%load_ext autoreload
%autoreload 2
from AP_class import alch_deriv,first_deriv_nuc_nuc,second_deriv_nuc_nuc
from AP_class import APDFT_perturbator as AP
from AP_symmetry import benz_Symm

In [2]:
benz_atom=""" 
C         6.95191249e-13  2.61173060e+00 -1.67580194e-08 ;
H         2.83052087e-13  4.63941350e+00 -1.15976219e-08 ;
C         2.26182505e+00  1.30586530e+00 -2.37508246e-08 ; 
H         4.01784995e+00  2.31970675e+00 -9.84687205e-09 ; 
C         2.26182505e+00 -1.30586530e+00  8.26065094e-09 ; 
H         4.01784995e+00 -2.31970675e+00  5.83890508e-08 ; 
C        -8.45954456e-13 -2.61173060e+00 -1.55922267e-08 ; 
H         1.49445304e-12 -4.63941350e+00 -3.26774154e-08 ; 
C        -2.26182505e+00 -1.30586530e+00 -8.28266973e-09 ; 
H        -4.01784995e+00 -2.31970675e+00  1.87236306e-09 ; 
C        -2.26182505e+00  1.30586530e+00  1.68546675e-08 ; 
H        -4.01784995e+00  2.31970675e+00  3.31289175e-08 ; 
"""
Benz = gto.M(atom=benz_atom, basis={"H":"pc-2",'C':bse.get_basis("pcX-2",fmt="nwchem",elements=[6])},unit='bohr')

In [3]:
benz_coords=Benz.atom_coords()

In [4]:
benz_dm0=np.load("benz_dm.npy")
BenzHF=scf.RHF(Benz)
BenzHF.scf(dm0=benz_dm0)

converged SCF energy = -230.788695455662


-230.78869545566204

In [5]:
apbz=AP(BenzHF,sites=[0,2,4,6,8,10],symm=benz_Symm(Benz))

In [6]:
apbz.build_all()

In [7]:
apbz.af(0)

No AF found for atom 0. Calculating it from code


array([[ 2.88913309e-13,  2.15252224e-02, -8.55158152e-10],
       [-1.05824131e-13,  7.83866964e-02,  6.27286882e-11],
       [ 6.76028944e-02, -3.29035758e-02, -9.90825538e-10],
       [ 9.50152738e-03, -5.77177984e-03,  3.70296269e-10],
       [ 2.91178600e-03,  9.40043921e-04, -1.87817581e-10],
       [ 1.70413431e-03, -5.34737950e-03,  2.06336919e-10],
       [-3.49314680e-14, -1.13075776e-02,  1.81584627e-10],
       [-3.56329804e-14, -2.43895882e-03,  2.29537636e-11],
       [-2.91178600e-03,  9.40043921e-04,  5.66206790e-12],
       [-1.70413431e-03, -5.34737950e-03, -9.18822380e-11],
       [-6.76028944e-02, -3.29035758e-02,  1.20210660e-09],
       [-9.50152738e-03, -5.77177984e-03,  7.40145691e-11]])

In [8]:
apbz.af(2)

array([[-6.22967797e-02,  4.20940361e-02,  1.20210660e-09],
       [-9.74927165e-03,  5.34267417e-03,  7.40145691e-11],
       [ 1.86413894e-02,  1.07626112e-02, -8.55158152e-10],
       [ 6.78848704e-02,  3.91933482e-02,  6.27286882e-11],
       [ 5.30611472e-03, -7.49976118e-02, -9.90825538e-10],
       [-2.47744275e-04, -1.11144540e-02,  3.70296269e-10],
       [ 2.26999491e-03, -2.05165868e-03, -1.87817581e-10],
       [-3.77889933e-03, -4.14951335e-03,  2.06336919e-10],
       [-9.79264947e-03, -5.65378881e-03,  1.81584627e-10],
       [-2.11220030e-03, -1.21947941e-03,  2.29537636e-11],
       [-6.41791082e-04,  2.99170260e-03,  5.66206790e-12],
       [-5.48303364e-03, -1.19786615e-03, -9.18822380e-11]])

In [10]:
mut_list1=["NBCCCC","NCBCCC","NCCBCC"]
mut_list2=["NBNBCC","NBBNCC","BNNBCC","BBNNCC","NBNCBC","BNBCNC","BNNCBC","NBBCNC"]#4-11
mut_list3=["NBCBNC","NNCBBC","NBCNBC","NNNBBB","NBNBNB","NNBBNB"] #12-17

In [19]:
charge2symbol={1:"H",2:"He",3:"Li",4:"Be",5:"B",6:"C",7:"N",8:"O",9:"F",10:"Ne"}
symbol2charge={"H":1,"He":2,"Li":3,"Be":4,"B":5,"C":6,"N":7,"O":8,"F":9,"Ne":10}
af_array=np.asarray([apbz.af(0),apbz.af(2),apbz.af(4),apbz.af(6),apbz.af(8),apbz.af(10)])

In [11]:
np.einsum("ijk,i->jk",af_array,[1,0,1,0,0,0])-apbz.af(0)-apbz.af(4)

array([[ 0.00000000e+00, -1.73472348e-18,  0.00000000e+00],
       [ 0.00000000e+00,  3.46944695e-18,  0.00000000e+00],
       [ 3.46944695e-18,  0.00000000e+00,  0.00000000e+00],
       [-8.67361738e-19,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  6.93889390e-18,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.16840434e-19,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  2.16840434e-19,  0.00000000e+00],
       [-3.46944695e-18,  1.73472348e-18,  0.00000000e+00],
       [ 0.00000000e+00, -4.33680869e-19,  6.46234854e-27]])

In [12]:
[symbol2charge[x]-6 for x in mut_list1[1]]

[1, 0, -1, 0, 0, 0]

In [22]:
h0=np.load("benz_hessian.npy")

In [14]:
apbz.af(2)

array([[-6.22967797e-02,  4.20940361e-02,  1.20198227e-09],
       [-9.74927165e-03,  5.34267417e-03,  7.40341603e-11],
       [ 1.86413894e-02,  1.07626112e-02, -8.55096555e-10],
       [ 6.78848704e-02,  3.91933482e-02,  6.27789755e-11],
       [ 5.30611472e-03, -7.49976118e-02, -9.90937821e-10],
       [-2.47744275e-04, -1.11144540e-02,  3.70405108e-10],
       [ 2.26999491e-03, -2.05165868e-03, -1.87821128e-10],
       [-3.77889933e-03, -4.14951335e-03,  2.06298232e-10],
       [-9.79264947e-03, -5.65378881e-03,  1.81718379e-10],
       [-2.11220030e-03, -1.21947941e-03,  2.29272695e-11],
       [-6.41791083e-04,  2.99170260e-03,  5.62097330e-12],
       [-5.48303364e-03, -1.19786615e-03, -9.19098632e-11]])

In [29]:
def nr_step(ic,g,h):
    ncoords=ic.shape[0]*ic.shape[1]
    p1cds=ic-np.linalg.solve((np.swapaxes(h,1,2)).reshape(ncoords,ncoords),g.reshape(-1)).reshape(ic.shape[0],ic.shape[1])
    #print (norm(p1cds[1]))
    return(p1cds)


In [18]:
def nr_DE(g,h):
    ncoords=g.shape[0]*g.shape[1]
    dr=-np.linalg.solve((np.swapaxes(h,1,2)).reshape(ncoords,ncoords),g.reshape(-1))
    de=0.5*dr.dot(g.reshape(-1))
    return de

In [134]:
nr_step(benz_coords,apbz.af(0)/100,h0)

array([[-1.05642564e-04,  2.61033716e+00,  7.01967017e-09],
       [-1.05639450e-04,  4.63608640e+00,  3.16127630e-08],
       [ 2.26070478e+00,  1.30610979e+00,  2.51980223e-08],
       [ 4.01568640e+00,  2.32154012e+00,  7.79425750e-08],
       [ 2.26166064e+00, -1.30548441e+00,  3.21071720e-08],
       [ 4.01795471e+00, -2.31862494e+00,  1.01677126e-07],
       [-1.05650593e-04, -2.61128185e+00, -4.19816836e-08],
       [-1.05653705e-04, -4.63891611e+00, -7.85356232e-08],
       [-2.26187194e+00, -1.30548440e+00, -5.98070619e-08],
       [-4.01816601e+00, -2.31862493e+00, -8.85774198e-08],
       [-2.26091607e+00,  1.30610980e+00, -9.62641729e-09],
       [-4.01589769e+00,  2.32154013e+00, -1.28607448e-08]])

In [135]:
benz_coords

array([[ 6.95191249e-13,  2.61173060e+00, -1.67580194e-08],
       [ 2.83052087e-13,  4.63941350e+00, -1.15976219e-08],
       [ 2.26182505e+00,  1.30586530e+00, -2.37508246e-08],
       [ 4.01784995e+00,  2.31970675e+00, -9.84687205e-09],
       [ 2.26182505e+00, -1.30586530e+00,  8.26065094e-09],
       [ 4.01784995e+00, -2.31970675e+00,  5.83890508e-08],
       [-8.45954456e-13, -2.61173060e+00, -1.55922267e-08],
       [ 1.49445304e-12, -4.63941350e+00, -3.26774154e-08],
       [-2.26182505e+00, -1.30586530e+00, -8.28266973e-09],
       [-4.01784995e+00, -2.31970675e+00,  1.87236306e-09],
       [-2.26182505e+00,  1.30586530e+00,  1.68546675e-08],
       [-4.01784995e+00,  2.31970675e+00,  3.31289175e-08]])

In [32]:
atomstr="{} {};H {} ;"*6

In [33]:
atomstr

'{} {};H {} ;{} {};H {} ;{} {};H {} ;{} {};H {} ;{} {};H {} ;{} {};H {} ;'

In [82]:
mut=mut_list2[1]
lstfrmt=[]
for i in range(6):
    lstfrmt.append(mut[i])
    lstfrmt.append(str(pg1[2*i])[1:-1])
    lstfrmt.append(str(pg1[2*i+1])[1:-1])
atomstr.format(*lstfrmt)

'N -1.05642669e-02  2.47238668e+00  2.36101094e-06;H -1.05639555e-02  4.30670354e+00  4.30944087e-06 ;B 2.14979822e+00 1.33031459e+00 4.87113387e-06;H 3.80149502e+00 2.50304332e+00 8.76909784e-06 ;B  2.24538437e+00 -1.26777618e+00  2.39291275e-06;H  4.02832593e+00 -2.21152580e+00  4.38719657e-06 ;N -1.05650697e-02 -2.56685557e+00 -2.65453791e-06;H -1.05653811e-02 -4.58967459e+00 -4.61849820e-06 ;C -2.26651411e+00 -1.26777549e+00 -5.16072189e-06;H -4.04945598e+00 -2.21152457e+00 -9.04310592e-06 ;C -2.17092716e+00  1.33031528e+00 -2.63125381e-06;H -3.82262365e+00  2.50304456e+00 -4.56583731e-06 ;'

In [91]:
molpg1=gto.M(atom=atomstr.format(*lstfrmt),unit="Bohr")
molpg1.atom_coords()

array([[-1.05642669e-02,  2.47238668e+00,  2.36101094e-06],
       [-1.05639555e-02,  4.30670354e+00,  4.30944087e-06],
       [ 2.14979822e+00,  1.33031459e+00,  4.87113387e-06],
       [ 3.80149502e+00,  2.50304332e+00,  8.76909784e-06],
       [ 2.24538437e+00, -1.26777618e+00,  2.39291275e-06],
       [ 4.02832593e+00, -2.21152580e+00,  4.38719657e-06],
       [-1.05650697e-02, -2.56685557e+00, -2.65453791e-06],
       [-1.05653811e-02, -4.58967459e+00, -4.61849820e-06],
       [-2.26651411e+00, -1.26777549e+00, -5.16072189e-06],
       [-4.04945598e+00, -2.21152457e+00, -9.04310592e-06],
       [-2.17092716e+00,  1.33031528e+00, -2.63125381e-06],
       [-3.82262365e+00,  2.50304456e+00, -4.56583731e-06]])

In [137]:
for idx,mut in enumerate(mut_list1):
    print([symbol2charge[x]-6 for x in mut])
    af=np.einsum("ijk,i->jk",af_array,[symbol2charge[x]-6 for x in mut])
    pg=nr_step(benz_coords,af,h0)
    lstfrmt=[]
    for i in range(6):
        lstfrmt.append(mut[i])
        lstfrmt.append(str(pg[2*i])[1:-1])
        lstfrmt.append(str(pg[2*i+1])[1:-1])
    atomstr.format(*lstfrmt)
    molp=gto.M(atom=atomstr.format(*lstfrmt),unit="Bohr")
    molp.tofile("./NR_H0/{}_NR.xyz".format(idx+1))


[1, -1, 0, 0, 0, 0]
[1, 0, -1, 0, 0, 0]
[1, 0, 0, -1, 0, 0]


In [139]:
for idx,mut in enumerate(mut_list2):
    af=np.einsum("ijk,i->jk",af_array,[symbol2charge[x]-6 for x in mut])
    pg=nr_step(benz_coords,af,h0)
    lstfrmt=[]
    for i in range(6):
        lstfrmt.append(mut[i])
        lstfrmt.append(str(pg[2*i])[1:-1])
        lstfrmt.append(str(pg[2*i+1])[1:-1])
    atomstr.format(*lstfrmt)
    molp=gto.M(atom=atomstr.format(*lstfrmt),unit="Bohr")
    molp.tofile("./NR_H0/{}_NR.xyz".format(idx+4))
    
for idx,mut in enumerate(mut_list3):
    af=np.einsum("ijk,i->jk",af_array,[symbol2charge[x]-6 for x in mut])
    pg=nr_step(benz_coords,af,h0)
    lstfrmt=[]
    for i in range(6):
        lstfrmt.append(mut[i])
        lstfrmt.append(str(pg[2*i])[1:-1])
        lstfrmt.append(str(pg[2*i+1])[1:-1])
    atomstr.format(*lstfrmt)
    molp=gto.M(atom=atomstr.format(*lstfrmt),unit="Bohr")
    molp.tofile("./NR_H0/{}_NR.xyz".format(idx+12))


In [140]:
import rmsd 

In [141]:
for i in range(4,18):
    print(i)
    rmsd.main(args=["./opt/{}_opt.xyz".format(i),"./pred_geoms/{}_p.xyz".format(i)])

4
0.06508065523817591
5
0.13132735437837767
6
0.08640737419107673
7
0.15292434639534427
8
0.07519094224058497
9
0.08390932797615752
10
0.10920925530150724
11
0.15117381124015006
12
0.09472227859300518
13
0.16463786587210355
14
0.07993302928665275
15
0.2131339425317265
16
0.0636595936520292
17
0.14159151060309583


In [145]:
for i in range(1,4):
    print(i)
    rmsd.main(args=["./opt/{}_opt.xyz".format(i),"./NR_H0/{}_NR.xyz".format(i)])

1
0.04022603342277137
2
0.03118568070832377
3
0.04219086509179594


In [142]:
for i in range(4,18):
    print(i)
    rmsd.main(args=["./opt/{}_opt.xyz".format(i),"./NR_H0/{}_NR.xyz".format(i)])
    rmsd.main(args=["./opt/{}_opt.xyz".format(i),"./pred_geoms/{}_p.xyz".format(i)])
    rmsd.main(args=["./opt/{}_opt.xyz".format(i),"./pred_geoms/{}_bg.xyz".format(i)])
    rmsd.main(args=["./NR_H0/{}_NR.xyz".format(i),"./pred_geoms/{}_bg.xyz".format(i)])

4
0.05145613760749521
0.06508065523817591
0.1132974447104944
0.09922193837826412
5
0.0792923344948646
0.13132735437837767
0.1907462624819973
0.1528530765891545
6
0.08154447769207164
0.08640737419107673
0.13339332603821155
0.1528541985851898
7
0.09177090723147235
0.15292434639534427
0.2179715197923148
0.20315574185906582
8
0.0432311765593216
0.07519094224058497
0.1263673603393583
0.12453102269853579
9
0.04612952822585621
0.08390932797615752
0.13952669074949411
0.12452905341430467
10
0.07534621475279375
0.10920925530150724
0.1735515397965274
0.18279908950357465
11
0.06971104758368292
0.15117381124015006
0.2198371540504253
0.18279935546300094
12
0.05646410895937914
0.09472227859300518
0.15876304297141489
0.13710983969022963
13
0.07996004470325228
0.16463786587210355
0.23568516763602587
0.2241110367116062
14
0.04242737086128693
0.07993302928665275
0.12933844027698854
0.12004335936462215
15
0.12965531657203813
0.2131339425317265
0.27815672340721465
0.2597740706839199
16
0.05523962110355735


In [143]:
for i in range(4,18):
    print(i)
    rmsd.main(args=["./pred_geoms/{}_p.xyz".format(i),"./NR_H0/{}_NR.xyz".format(i)])

4
0.03827002468384104
5
0.08672385592944967
6
0.08708471482329563
7
0.12750185569257078
8
0.06454451498357285
9
0.06470099925973614
10
0.10867539332270756
11
0.10834467204514125
12
0.06447342744158287
13
0.1458997833420189
14
0.06483952191219988
15
0.1824334699148727
16
0.021104609553829725
17
0.11329044454932372


# Energies

In [25]:
ve=[]
for m in mut_list1:
    ve.append(apbz.APDFT3([symbol2charge[x]-6 for x in m])+absec("CCCCCC",m))
for m in mut_list2:
    ve.append(apbz.APDFT3([symbol2charge[x]-6 for x in m])+absec("CCCCCC",m))
for m in mut_list3:
    ve.append(apbz.APDFT3([symbol2charge[x]-6 for x in m])+absec("CCCCCC",m))

In [20]:
ve

[-234.19061699804783,
 -234.11416772261225,
 -234.13245191013118,
 -237.68727200366925,
 -237.49671255053715,
 -237.49889760583955,
 -237.38147490196437,
 -237.58157466523903,
 -237.56693404206675,
 -237.4516963930366,
 -237.46415196189278,
 -237.62910691557607,
 -237.32330981386733,
 -237.5559701657905,
 -240.66706626846738,
 -241.27866047186282,
 -240.89972662084446]

In [26]:
ve

[-234.195808181066,
 -234.11935890563043,
 -234.13764309314936,
 -237.69765436970562,
 -237.50709491657352,
 -237.5092799718759,
 -237.3918572680007,
 -237.5919570312754,
 -237.57731640810312,
 -237.46207875907294,
 -237.47453432792912,
 -237.63948928161244,
 -237.33369217990366,
 -237.56635253182685,
 -240.6826398175219,
 -241.29423402091734,
 -240.91530016989898]

In [23]:
der=[]
for m in mut_list1:
    af=np.einsum("ijk,i->jk",af_array,[symbol2charge[x]-6 for x in m])
    der.append(nr_DE(af,h0))
for m in mut_list2:
    af=np.einsum("ijk,i->jk",af_array,[symbol2charge[x]-6 for x in m])
    der.append(nr_DE(af,h0))
for m in mut_list3:
    af=np.einsum("ijk,i->jk",af_array,[symbol2charge[x]-6 for x in m])
    der.append(nr_DE(af,h0))

In [24]:
der

[-0.02996032447921387,
 -0.04740279075758845,
 -0.04884167834669828,
 -0.04391707031649379,
 -0.07592422760387703,
 -0.07592422760387703,
 -0.11368693542868308,
 -0.05848176150115905,
 -0.05848176150115905,
 -0.0962444686631195,
 -0.0962444686631195,
 -0.06279842389464045,
 -0.13256828900228648,
 -0.057042874020063264,
 -0.1814099667100488,
 -0.041870237287339934,
 -0.10588455240080201]

In [40]:
re=[]
for i in range(len(ve)):
    re.append(ve[i]+der[i])

In [41]:
re

[-234.22576850554515,
 -234.16676169638782,
 -234.18648477149603,
 -237.74157144002226,
 -237.58301914417692,
 -237.5852041994793,
 -237.50554420342903,
 -237.65043879277619,
 -237.6357981696039,
 -237.55832322773583,
 -237.570778796592,
 -237.70228770550727,
 -237.46626046890563,
 -237.62339540584637,
 -240.8640497842316,
 -241.33610425820535,
 -241.0211847222992]

In [13]:
ve2=[]
for m in mut_list1:
    ve2.append(apbz.APDFT2([symbol2charge[x]-6 for x in m])+absec("CCCCCC",m))
for m in mut_list2:
    ve2.append(apbz.APDFT2([symbol2charge[x]-6 for x in m])+absec("CCCCCC",m))
for m in mut_list3:
    ve2.append(apbz.APDFT2([symbol2charge[x]-6 for x in m])+absec("CCCCCC",m))

In [14]:
ve2

[-234.1958081810586,
 -234.11935890563154,
 -234.13764309315025,
 -237.69765436971124,
 -237.5081874437176,
 -237.50818744474554,
 -237.39185726800991,
 -237.58463671943753,
 -237.5846367199536,
 -237.46830654376794,
 -237.46830654324776,
 -237.63948928161614,
 -237.33369217990997,
 -237.56635253181224,
 -240.68263981753205,
 -241.2942340209282,
 -240.91530016990546]

In [25]:
re2=[]
for i in range(len(ve2)):
    re2.append(ve2[i]+der[i])

In [26]:
re2

[-234.22576850553781,
 -234.16676169638913,
 -234.18648477149694,
 -237.74157144002774,
 -237.58411167132147,
 -237.58411167234942,
 -237.5055442034386,
 -237.64311848093868,
 -237.64311848145476,
 -237.56455101243105,
 -237.56455101191088,
 -237.70228770551077,
 -237.46626046891225,
 -237.6233954058323,
 -240.8640497842421,
 -241.33610425821553,
 -241.02118472230626]

In [27]:
np.asarray(ve2)-np.asarray(re2)

array([0.02996032, 0.04740279, 0.04884168, 0.04391707, 0.07592423,
       0.07592423, 0.11368694, 0.05848176, 0.05848176, 0.09624447,
       0.09624447, 0.06279842, 0.13256829, 0.05704287, 0.18140997,
       0.04187024, 0.10588455])

In [34]:
ve2.sort(),re2.sort()

In [37]:
ve2

[-241.2942340209282,
 -240.91530016990546,
 -240.68263981753205,
 -237.69765436971124,
 -237.63948928161614,
 -237.5846367199536,
 -237.58463671943753,
 -237.56635253181224,
 -237.50818744474554,
 -237.5081874437176,
 -237.46830654376794,
 -237.46830654324776,
 -237.39185726800991,
 -237.33369217990997,
 -234.1958081810586,
 -234.13764309315025,
 -234.11935890563154]

In [38]:
re2

[-234.22576850553781,
 -234.16676169638913,
 -234.18648477149694,
 -237.74157144002774,
 -237.58411167132147,
 -237.58411167234942,
 -237.5055442034386,
 -237.64311848093868,
 -237.64311848145476,
 -237.56455101243105,
 -237.56455101191088,
 -237.70228770551077,
 -237.46626046891225,
 -237.6233954058323,
 -240.8640497842421,
 -241.33610425821553,
 -241.02118472230626]