In [1]:
import qml
import numpy as np

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed',)).History will not be written to the database.


In [2]:
c1 = qml.Compound('../../test/c20-opposite.xyz')
c2 = qml.Compound('../../test/c20-other.xyz')

In [13]:
r1 = qml.fchl.generate_representation(c1.coordinates, c1.nuclear_charges, max_size=23)
r2 = qml.fchl.generate_representation(c2.coordinates, c2.nuclear_charges, max_size=23)

In [14]:
b = qml.fchl.get_atomic_kernels(r1, r2, [0.5,])[0][0]
b

array([0.9998336 , 0.99869457, 0.99869456, 0.9998336 , 0.99412284,
       0.99999999, 0.99555625, 0.99570452, 0.99320025, 0.99570451,
       0.99555625, 0.99999999, 0.99435597, 0.63519233, 0.99435592,
       0.63523849, 0.99306667, 0.99869434, 0.99869433, 0.99306668,
       0.01198102, 0.01198102, 0.01198102])

In [33]:
r1 = qml.fchl.generate_representation(c1.coordinates, c1.nuclear_charges, max_size=23)
r2 = qml.fchl.generate_representation(c2.coordinates, c2.nuclear_charges, max_size=23)

In [34]:
qml.fchl.get_atomic_kernels(r1, r2, [0.5,])[0][0]

array([0.9998336 , 0.99869457, 0.99869456, 0.9998336 , 0.99412284,
       0.99999999, 0.99555625, 0.99570452, 0.99320025, 0.99570451,
       0.99555625, 0.99999999, 0.99435597, 0.63519233, 0.99435592,
       0.63523849, 0.99306667, 0.99869434, 0.99869433, 0.99306668,
       0.01198102, 0.01198102, 0.01198102])

In [20]:
np.array_equal(a, b)

False

In [35]:
a

array([0.9998336 , 0.99869457, 0.99869456, 0.9998336 , 0.99412284,
       0.99999999, 0.99555625, 0.99570452, 0.99320025, 0.99570451,
       0.99555625, 0.99999999, 0.99435597, 0.63519233, 0.99435592,
       0.63523849, 0.99306667, 0.99869434, 0.99869433, 0.99306668,
              inf,        inf,        inf])

In [36]:
b

array([0.9998336 , 0.99869457, 0.99869456, 0.9998336 , 0.99412284,
       0.99999999, 0.99555625, 0.99570452, 0.99320025, 0.99570451,
       0.99555625, 0.99999999, 0.99435597, 0.63519233, 0.99435592,
       0.63523849, 0.99306667, 0.99869434, 0.99869433, 0.99306668,
       0.01198102, 0.01198102, 0.01198102])