In [ ]:
from pyscf import gto, scf,dft
from pyscf.geomopt.berny_solver import optimize

In [6]:
benz_atom="""C 0.0 2.6196127020137916 0.0;
H 0.0 4.652157753665769 0.0;
C 2.268651148020338 1.309806351006896 0.0;
H 4.028886797087305 2.326078876832885 0.0;
C 2.2686511480203384 -1.3098063510068951 0.0;
H 4.028886797087305 -2.3260788768328835 0.0;
C 3.208100310526939e-16 -2.6196127020137916 0.0;
H 5.697250102155325e-16 -4.652157753665769 0.0;
C -2.2686511480203375 -1.309806351006897 0.0;
H -4.028886797087303 -2.3260788768328866 0.0;
C -2.2686511480203393 1.309806351006894 0.0;
H -4.028886797087306 2.3260788768328813 0.0
"""

mol = gto.M(atom=benz_atom, basis='MG3S',unit='bohr')
mf = dft.RKS(mol)
mf.xc = 'lda,vwn'
mf.kernel()

KeyError: 'Invalid basis name MG3S'

In [5]:
atoms_coords=[[ 3.51767583, -0.25423489 , 4.04215521],\
 [ 2.52061864, -0.11916074,  2.27612256],\
 [-0.0966844 , -0.01131471,  2.25456475],\
 [-1.13038502, -0.06283247,  4.00386424],\
 [-1.38173535,  0.16255151, -0.02156913],\
 [-3.41249094,  0.24616206, -0.03829955],\
 [-0.04946481,  0.22899259, -2.27612247],\
 [-1.04652182,  0.36406487, -4.0421554 ],\
 [ 2.56783853,  0.12114771, -2.25456461],\
 [ 3.60153856,  0.17266112, -4.00386438],\
 [ 3.85288933, -0.05271966,  0.02156911],\
 [ 5.88364489, -0.1363321 ,  0.03829968]]


In [8]:
import numpy as np
atoms_coords=np.asarray(atoms_coords)
for x in atoms_coords:
    for y in atoms_coords:
        print (np.linalg.norm(x-y))

0.0
2.0325450516519776
4.03956553836423
4.652157644584728
6.379012174736962
8.057773862301435
7.271769659756346
9.30431474212046
6.379011168232494
8.057772918337966
4.039565455097542
4.652157538806984
2.0325450516519776
0.0
2.6196127020137916
4.039565807378785
4.537302674206785
6.379012442356926
5.239224608118428
7.2717696904777345
4.537301411803676
6.379011195945436
2.6196127323426155
4.039565775679956
4.03956553836423
2.6196127020137916
0.0
2.0325451426962364
2.6196127282934105
4.039566065310839
4.537301397701544
6.379011334127669
5.239224782582062
7.271769753170675
4.5373027832457495
6.379012354991674
4.652157644584728
4.039565807378785
2.0325451426962364
0.0
4.039565415133329
4.652157903044149
6.379011165048003
8.057773043619376
7.271769922303632
9.304314894147673
6.379012464223263
8.057773889450656
6.379012174736962
4.537302674206785
2.6196127282934105
4.039565415133329
0.0
2.032544931198552
2.6196125613854835
4.039565533503086
4.5373028245790605
6.379012190337434
5.23922686327368

In [9]:
ch_dist=2.0325450516519776
cc_dist=2.6196127020137916

In [12]:
ang=[]
for i in range(6):
    ang.append([np.sin(np.pi/3.*i),np.cos(np.pi/3.*i),0])
    ang.append([np.sin(np.pi/3.*i),np.cos(np.pi/3.*i),0])
ang=np.asarray(ang)

In [17]:
#ang[0::2]/=cc_dist
#ang[1::2]/=(cc_dist+ch_dist)

In [19]:
ang

array([[ 0.00000000e+00,  2.61961270e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.65215775e+00,  0.00000000e+00],
       [ 2.26865115e+00,  1.30980635e+00,  0.00000000e+00],
       [ 4.02888680e+00,  2.32607888e+00,  0.00000000e+00],
       [ 2.26865115e+00, -1.30980635e+00,  0.00000000e+00],
       [ 4.02888680e+00, -2.32607888e+00,  0.00000000e+00],
       [ 3.20810031e-16, -2.61961270e+00,  0.00000000e+00],
       [ 5.69725010e-16, -4.65215775e+00,  0.00000000e+00],
       [-2.26865115e+00, -1.30980635e+00,  0.00000000e+00],
       [-4.02888680e+00, -2.32607888e+00,  0.00000000e+00],
       [-2.26865115e+00,  1.30980635e+00,  0.00000000e+00],
       [-4.02888680e+00,  2.32607888e+00,  0.00000000e+00]])

In [22]:
mol.coords=ang
mol.atoms

array([[ 0.00000000e+00,  2.61961270e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.65215775e+00,  0.00000000e+00],
       [ 2.26865115e+00,  1.30980635e+00,  0.00000000e+00],
       [ 4.02888680e+00,  2.32607888e+00,  0.00000000e+00],
       [ 2.26865115e+00, -1.30980635e+00,  0.00000000e+00],
       [ 4.02888680e+00, -2.32607888e+00,  0.00000000e+00],
       [ 3.20810031e-16, -2.61961270e+00,  0.00000000e+00],
       [ 5.69725010e-16, -4.65215775e+00,  0.00000000e+00],
       [-2.26865115e+00, -1.30980635e+00,  0.00000000e+00],
       [-4.02888680e+00, -2.32607888e+00,  0.00000000e+00],
       [-2.26865115e+00,  1.30980635e+00,  0.00000000e+00],
       [-4.02888680e+00,  2.32607888e+00,  0.00000000e+00]])

In [43]:
string=''
for i in range(6):
    string+='C '+str(ang[2*i,0])+' '+str(ang[2*i,1])+' '+str(ang[2*i,2]) +';' 
    string +='H '+str(ang[2*i+1,0])+' '+str(ang[2*i+1,1])+' '+str(ang[2*i+1,2]) +';'

In [44]:
string

'C 0.0 2.6196127020137916 0.0;H 0.0 4.652157753665769 0.0;C 2.268651148020338 1.309806351006896 0.0;H 4.028886797087305 2.326078876832885 0.0;C 2.2686511480203384 -1.3098063510068951 0.0;H 4.028886797087305 -2.3260788768328835 0.0;C 3.208100310526939e-16 -2.6196127020137916 0.0;H 5.697250102155325e-16 -4.652157753665769 0.0;C -2.2686511480203375 -1.309806351006897 0.0;H -4.028886797087303 -2.3260788768328866 0.0;C -2.2686511480203393 1.309806351006894 0.0;H -4.028886797087306 2.3260788768328813 0.0;'

In [49]:
#mol = gto.M(atom=string, basis='6-31G*',unit='bohr')
#mf = scf.RHF(mol)
#mol_eq = optimize(mf)
print(mol_eq.atom_coords())

[[ 0.00000000e+00  2.61961270e+00  0.00000000e+00]
 [ 0.00000000e+00  4.65215775e+00  0.00000000e+00]
 [ 2.26865115e+00  1.30980635e+00  0.00000000e+00]
 [ 4.02888680e+00  2.32607888e+00  0.00000000e+00]
 [ 2.26865115e+00 -1.30980635e+00  0.00000000e+00]
 [ 4.02888680e+00 -2.32607888e+00  0.00000000e+00]
 [ 3.20810031e-16 -2.61961270e+00  0.00000000e+00]
 [ 5.69725010e-16 -4.65215775e+00  0.00000000e+00]
 [-2.26865115e+00 -1.30980635e+00  0.00000000e+00]
 [-4.02888680e+00 -2.32607888e+00  0.00000000e+00]
 [-2.26865115e+00  1.30980635e+00  0.00000000e+00]
 [-4.02888680e+00  2.32607888e+00  0.00000000e+00]]
