#### Why are some of the positions negative and so different from intial//final geometry?

- Run MD for 1 step

- compute absoulte coordinates for final.geom
- add length of unit cell to negative values in MD-1 (this shifts the coordinate into the unit cell where everything is positive)

- compare positions from final.geom and ion.1.dat $\rightarrow$ they are identical (within numerical precision)


In [6]:
from ase import Atoms
import numpy as np
from ase.calculators.general import Calculator
from ase.md.verlet import VelocityVerlet
from ase import units
length = 3.97

#### inital geometry file

In [9]:
frac1_i =  np.array([0,0,0])
frac2_i = np.array([0.5, 0.6, 0])
frac3_i = np.array([0,  0.5, 0.5])
frac4_i = np.array([0.5, 0, 0.5])

fracs_i = [frac1_i,frac2_i,frac3_i,frac4_i]

abs_i = []
for f in fracs_i:
    abs_i.append(length*f)
abs_i = np.array(abs_i)

In [13]:
abs_i

array([[0.   , 0.   , 0.   ],
       [1.985, 2.382, 0.   ],
       [0.   , 1.985, 1.985],
       [1.985, 0.   , 1.985]])

#### final geometry file

In [10]:
frac1 =  np.array([0.748809049954232,   0.724820103634806,   0.748922820058295])
frac2 =    np.array([0.251440730256209,   0.324518387592636,   0.750709679690510])
frac3 =    np.array([0.750092630352505,   0.223760753399931,   0.250954990569445])
frac4 =    np.array([0.249657589437055,   0.726900738707145,   0.249412509681749])

fracs = [frac1,frac2,frac3,frac4]

abs_ = []
for f in fracs:
    abs_.append(length*f)
abs_ = np.array(abs_)

In [12]:
abs_

array([[2.97277193, 2.87753581, 2.9732236 ],
       [0.9982197 , 1.288338  , 2.98031743],
       [2.97786774, 0.88833019, 0.99629131],
       [0.99114063, 2.88579593, 0.99016766]])

#### md file

In [16]:
abs1_md =  np.array([-9.97228072E-01,   -1.09246419E+00,   -9.96776404E-01])
abs2_md =  np.array([9.98219699E-01,    1.28833800E+00,   -9.89682572E-01])
abs3_md =  np.array([-9.92132258E-01,    8.88330191E-01,    9.96291313E-01])
abs4_md =  np.array([9.91140630E-01,   -1.08420407E+00,    9.90167663E-01])
abs_md = [abs1_md, abs2_md, abs3_md, abs4_md]

for atom in abs_md:
    for i,c in enumerate(atom):
        if c < 0:
            atom[i] = c + length

In [18]:
abs_md

[array([2.97277193, 2.87753581, 2.9732236 ]),
 array([0.9982197 , 1.288338  , 2.98031743]),
 array([2.97786774, 0.88833019, 0.99629131]),
 array([0.99114063, 2.88579593, 0.99016766])]

In [20]:
np.allclose(abs_, abs_md)

True

In [21]:
abs_ - abs_md

array([[ 3.18300941e-10,  1.43017953e-09, -3.68569175e-10],
       [ 1.17149845e-10, -1.25723498e-09,  3.71324305e-10],
       [ 4.99444930e-10, -2.27384778e-12, -4.39303371e-10],
       [ 6.51083631e-11,  2.66736544e-09,  4.36543579e-10]])