## Simple MD without thermostat

In [1]:
from ase import Atoms
import numpy as np
from ase.calculators.general import Calculator
from ase.md.verlet import VelocityVerlet
from ase import units

### calculator

In [2]:
class OFDFT_calculator(Calculator):
    name = 'OFDFT_calculator'
    implemented_properties = ['forces']

    def __init__(self, forces):
        self.forces = forces
#         self.nAtoms = atoms.get_number_of_atoms()

    def get_forces(self, atoms=None):
        return(self.forces)

### MD run

In [3]:
# create atoms object

at1 = [0,0,0]
at2 = [0.5,0.5,0]
at3 = [0,0.5,0.5]
at4 = [0.5,0,0.5]
cell1 = [3.9691, 0, 0]
cell2 = [0, 3.9691, 0]
cell3 = [0, 0, 3.9691]

atoms = Atoms('Al4',
             positions=[at1,at2, at3, at4],
             cell=[cell1, cell2, cell3],
             pbc=True)

# is this correct or must I use something like this for crystals?

# # Set up a crystal
# atoms = FaceCenteredCubic(directions=[[1, 0, 0], [0, 1, 0], [0, 0, 1]],
#                           symbol='Cu',
#                           size=(size, size, size),
#                           pbc=True)

forces_nuclei = np.array([[0.0,0,0],[0,0,0],[0,0,0],[0,0,0]])

In [4]:
# set the forces from the OFDFT code
# improvement: call ofdft in this function?
# get_forces reads forces from file
atoms.set_calculator(OFDFT_calculator(forces_nuclei))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:


# We want to run MD with constant energy using the VelocityVerlet algorithm.
dyn = VelocityVerlet(atoms, 5 * units.fs)  # 5 fs time step.

# run only for one step
f=dyn.run(1)

# get new positions for force calculations
atoms.get_positions()

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0. ],
       [0. , 0.5, 0.5],
       [0.5, 0. , 0.5]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])