In [1]:
import pyscf.qmmm
from pyscf import gto, scf
import numpy as np
#import matplotlib.pyplot as plt
# from pyscf.geomopt.berny_solver import optimize
from pyscf.grad import rhf as grhf
#from pyscf.hessian import rhf as hrhf
from pyscf import lib
import inspect
from functools import reduce
from pyscf.scf import cphf
angstrom = 1 / 0.52917721067
from pyscf.scf._response_functions import _gen_rhf_response 
def DeltaV(mol,dL):
    mol.set_rinv_orig_(mol.atom_coords()[0])
    dV=mol.intor('int1e_rinv')*dL[0]
    mol.set_rinv_orig_(mol.atom_coords()[1])
    dV+=mol.intor('int1e_rinv')*dL[1]
    return -dV.reshape((1,dV.shape[0],dV.shape[1]))

def fc(calc,deltaZ):
    mf = pyscf.qmmm.mm_charge(calc, calc.mol.atom_coords(), deltaZ)  # now is add_mm_charge
    class NoSelfQMMM(mf.__class__):
        def energy_nuc(self):
            q = self.mol.atom_charges().astype(np.float).copy()
            q1 =q+ np.asarray(deltaZ) 
            return self.mol.energy_nuc(q1)
    return(NoSelfQMMM(mf,mf.mm_mol))

In [2]:
import time
from functools import reduce
import numpy
from pyscf import lib
from pyscf.lib import logger
from pyscf.scf import cphf
from pyscf.prop.nmr import rhf as rhf_nmr

def polarizability(polobj, with_cphf=True):
    mf = polobj._scf
    mol = mf.mol
    mo_energy = mf.mo_energy
    mo_coeff = mf.mo_coeff
    mo_occ = mf.mo_occ
    occidx = mo_occ > 0
    orbo = mo_coeff[:, occidx]
    orbv = mo_coeff[:,~occidx]

    charges = mol.atom_charges()
    coords  = mol.atom_coords()
    charge_center = numpy.einsum('i,ix->x', charges, coords) / charges.sum()
    int_r=DeltaV(mol,[.0001,-.0001])    ########   .001 as finite difference intervall  
    h1 = lib.einsum('xpq,pi,qj->xij', int_r, mo_coeff.conj(), orbo) #going to molecular orbitals?
    print(h1.shape, "shape (1, n ao, nocc)" )
    #print(mo_energy, mo_occ,h1)
    s1 = numpy.zeros_like(h1)
    vind = polobj.gen_vind(mf, mo_coeff, mo_occ)
    if with_cphf:
        mo1 = cphf.solve(vind, mo_energy, mo_occ, h1, s1, polobj.max_cycle_cphf, polobj.conv_tol)[0]
    else:
        mo1 = rhf_nmr._solve_mo1_uncoupled(mo_energy, mo_occ, h1, s1)[0]
    #e2 = numpy.einsum('xpi,ypi->xy', h1, mo1)
    # *-1 from the definition of dipole moment. *2 for double occupancy
    #e2 = (e2 + e2.T) * -2
    #return e2
    return mo1

In [3]:
mol = gto.M(atom='C 0 0 0; O 0 0 2.0', unit="Bohr",basis="sto-3g")
mf = scf.RHF(mol)
e=mf.scf()

converged SCF energy = -111.199724042755


In [4]:
g = mf.Gradients()
g.kernel()

--------------- RHF gradients ---------------
         x                y                z
0 C     0.0000000000    -0.0000000000     0.3426279915
1 O    -0.0000000000     0.0000000000    -0.3426279915
----------------------------------------------


array([[ 2.05291371e-16, -3.86540155e-16,  3.42627991e-01],
       [-2.05291371e-16,  3.86540155e-16, -3.42627991e-01]])

In [5]:
mol.atom_charge(0)

6

In [6]:
mf1=fc(mf,[.0001,-.0001])
mf1.scf()

converged SCF energy = -111.198995727549


-111.198995727549

In [7]:
C1=mf1.mo_coeff


In [8]:
mf2=fc(mf,[.0001,-.0001])
mf2.scf()

converged SCF energy = -111.198995727549


-111.19899572754903

In [9]:
e=mf.mo_energy
e1=mf1.mo_energy
e2=mf2.mo_energy

In [10]:
e,e1,e2

(array([-20.46076589, -11.10193184,  -1.52172836,  -0.71090808,
         -0.5989603 ,  -0.5989603 ,  -0.45135035,   0.34504015,
          0.34504015,   1.17302526]),
 array([-20.46017744, -11.10237896,  -1.52171628,  -0.71090629,
         -0.59895416,  -0.59895416,  -0.45136514,   0.34503314,
          0.34503314,   1.17302357]),
 array([-20.46017744, -11.10237896,  -1.52171628,  -0.71090629,
         -0.59895416,  -0.59895416,  -0.45136514,   0.34503314,
          0.34503314,   1.17302357]))

In [11]:
(e1-e)/.001,(e2-e)/.0001

(array([ 0.58844667, -0.44711917,  0.01208183,  0.00179161,  0.00614406,
         0.00614406, -0.01479785, -0.00701284, -0.00701284, -0.00169259]),
 array([ 5.88446669, -4.47119171,  0.12081825,  0.0179161 ,  0.0614406 ,
         0.0614406 , -0.14797845, -0.07012837, -0.07012837, -0.01692594]))

## Obtaining derivatives of W
$$W=  \sum_i ^{mo.occ.} \epsilon_i C_{\mu i} C_{\nu i}^\dagger 
$$

$$ \frac{\partial W}{\partial Z_I}= \sum_i ^{mo.occ.} \left( \epsilon_i (CU)_{\mu i} C_{\nu i}^\dagger + 
\epsilon_i C_{\mu i} (CU)^\dagger_{\nu i}   +\frac{\partial \epsilon_i}{\partial Z_I} C_{\mu i} C_{\nu i}^\dagger \right)$$

In [12]:
g1=mf1.Gradients()

In [13]:
W1=g1.make_rdm1e()
W=g.make_rdm1e()
dW=W1-W

In [14]:
o=mf.mo_occ
e=mf.mo_energy
C=mf.mo_coeff
S=mf.get_ovlp()
np.allclose(C@np.diag(o*e)@C.T,g.make_rdm1e())

True

In [15]:
plo=mf.Polarizability()
pa=polarizability(plo)
nao=mol.nao
nocc=mol.nelectron//2 #RHF
U=np.zeros((nao,nao))
U[:,:nocc]=pa[0,:,:nocc]
U=U.T-U
O=np.diag(mf.mo_occ)
dP_app=C@(U@O-O@U)@C.T

(1, 10, 7) shape (1, n ao, nocc)


In [16]:
np.allclose(C1@np.diag(o*e1)@C1.T,g1.make_rdm1e())

True

In [17]:
print(C1-C),print(C@U) #are different ! Orbital Mixing !!!! 

[[ 1.40205359e-07  2.31233600e-06 -2.72598827e-06  4.07647113e-07
  -1.24413587e-16  1.34530425e-16  1.26063071e-05  1.19977326e-17
  -2.13196125e-16  4.78066597e-06]
 [-3.24642228e-06 -9.69584425e-06  3.43116823e-05 -3.51273010e-05
   5.06804051e-16 -1.15461180e-15 -2.71781174e-05 -6.89611244e-17
   1.37962014e-15 -1.20774778e-06]
 [ 8.39139943e-17  4.98305722e-19 -9.13333724e-17 -7.27427095e-17
   9.10101459e-03 -8.23754986e-02 -1.31245273e-16  2.49797991e-03
   1.32972726e-01 -1.04014233e-16]
 [ 2.04314140e-18  5.80946329e-19  5.74382287e-16  1.59165165e-15
   8.23754986e-02  9.10101459e-03  7.83548562e-16 -1.32972726e-01
   2.49797991e-03 -5.68519230e-16]
 [-2.71612380e-06 -2.29727940e-06  1.57660300e-05  1.80328265e-05
   1.25604753e-16  2.38544262e-15 -1.26890884e-05  2.82331355e-17
   7.20357136e-17 -6.33976080e-06]
 [-1.66748285e-06 -1.12028994e-07  6.79405391e-07 -9.03341682e-06
   3.26937129e-17  2.84281902e-16 -3.92214702e-06 -5.51507939e-17
   9.54019743e-17  4.90498149e-06

(None, None)

In [18]:
dC=C@U

In [36]:
print(np.linalg.norm((C+dC)@np.diag(o*e1)@(C+dC).T-W1),np.linalg.norm(W1))
print(np.linalg.norm((C1)@np.diag(o*e1)@(C1).T-W1))

0.0011438938701722023 46.33860211065486
0.0


In [20]:
print(np.linalg.norm(dW-C@np.diag(o*(e1 -e))@C.T-dC@np.diag(o*e)@C.T-C@np.diag(o*e)@(dC).T))
print(np.linalg.norm(dW))

0.0011438977657250253
0.0017473265434270959


In [21]:
print(np.linalg.norm((C+dC)@np.diag(o*e1)@(C+dC).T-W),np.linalg.norm(dW))

0.0015202689472349803 0.0017473265434270959


In [22]:
F=mf.get_fock()

In [23]:
F1=mf1.get_fock()
print(mf1.mo_energy)
np.sort(np.linalg.eig(np.linalg.inv(S)@F1)[0])

[-20.46017744 -11.10237896  -1.52171628  -0.71090629  -0.59895416
  -0.59895416  -0.45136514   0.34503314   0.34503314   1.17302357]


array([-20.46017704, -11.1023791 ,  -1.52171615,  -0.71090614,
        -0.59895404,  -0.59895404,  -0.4513652 ,   0.34503314,
         0.34503314,   1.17302361])

In [24]:
S1=mf1.get_ovlp()
np.allclose(S,S1)
dV=DeltaV(mol,[.0001,-.0001])

In [25]:
np.linalg.norm(F+dV-F1)

0.0001701633130845573

In [26]:
np.linalg.norm(dV)

0.000899137263275962

In [27]:
np.linalg.norm(F-F1)

0.0007564728021069253

In [28]:
g_ijkl=mf.mol.intor('int2e_sph')

In [29]:
dF2el=np.einsum('ijkl,kl->ij',g_ijkl,dP_app)*2-np.einsum('ijkl,jl->ik',g_ijkl,dP_app)

In [30]:
np.linalg.norm(F1-F-dV+dF2el/2)

1.888669504896173e-09

In [31]:
np.allclose(np.sort(np.linalg.eig(np.linalg.inv(S)@(F+dV-dF2el/2))[0]),e1)

True

In [32]:
#dP_app=C@(U@O-O@U)@C.T
#dF2el=np.einsum('ijkl,kl->ij',g_ijkl,dP_app)*2-np.einsum('ijkl,jl->ik',g_ijkl,dP_app)
#e1_app=np.sort(np.linalg.eig(np.linalg.inv(S)@(F+dV-dF2el/2))