In [44]:
from pyscf import gto,scf
import numpy as np
#molecule with fractional charges 
%load_ext autoreload
%autoreload 2
from FcMole import FcM, FcM_like
from AP_class import APDFT_perturbator as AP

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [45]:
hcn=gto.M(atom= "N 0 0 0; C 0 0 2.1; H 0 0 3.4",unit="Bohr", basis="sto-3g" )

In [46]:
mf_hcn=scf.RHF(hcn)
mf_hcn.scf()
ap_hcn=AP(mf_hcn,sites=[0,1,2])

converged SCF energy = -91.3851073699862


In [47]:
h=ap_hcn.build_hessian(0,1,2)
ch2=ap_hcn.build_cubic_hessian2(0,1,2)
ch,ch2

(array([[[-0.06736416, -0.01498935, -0.00057113],
         [-0.01498935,  0.0071365 , -0.00846982],
         [-0.00057113, -0.00846982,  0.01068536]],
 
        [[-0.01498935,  0.0071365 , -0.00846982],
         [ 0.0071365 , -0.17087998,  0.0521149 ],
         [-0.00846982,  0.0521149 ,  0.01418075]],
 
        [[-0.00057113, -0.00846982,  0.01068536],
         [-0.00846982,  0.0521149 ,  0.01418075],
         [ 0.01068536,  0.01418075, -0.03847488]]]),
 array([[[ 0.06736416,  0.01498935,  0.00057113],
         [ 0.01498935, -0.0071365 ,  0.00846982],
         [ 0.00057113,  0.00846982, -0.01068536]],
 
        [[ 0.01498935, -0.0071365 ,  0.00846982],
         [-0.0071365 ,  0.17087998, -0.0521149 ],
         [ 0.00846982, -0.0521149 , -0.01418075]],
 
        [[ 0.00057113,  0.00846982, -0.01068536],
         [ 0.00846982, -0.0521149 , -0.01418075],
         [-0.01068536, -0.01418075,  0.03847488]]]))

In [23]:
sum(sum(sum(ch)))

-0.12186684902439789

In [9]:
# check FD scheme third deriv

In [16]:
def E(dz):
    fm=FcM_like(hcn,fcs=dz)
    mf=scf.RHF(fm)
    return mf.scf(dm0=mf.init_guess_by_1e())

In [30]:
def H(dz):
    fm=FcM_like(hcn,fcs=dz)
    mf=scf.RHF(fm)
    mf.scf(dm0=mf.init_guess_by_1e())
    ap=AP(mf,sites=[0,1,2])
    return ap.build_hessian(0,1,2)

In [17]:
E([0,0,0])
#−1/2 	1 	0 	−1 	1/2

converged SCF energy = -91.3851073699861


-91.38510736998606

In [19]:
(1/2*E([0.1,0.1,0.1])-E([0.05,0.05,0.05])+E([-0.05,-0.05,-0.05])-1/2*E([-0.1,-0.1,-0.1]))/.05**3

converged SCF energy = -94.6893153011456
converged SCF energy = -93.0406779452095
converged SCF energy = -89.7226178829943
converged SCF energy = -88.0532257235797


0.1221874577481685

In [25]:
(1/2*E([0.1,0.,0.])-E([0.05,0.,0.])+E([-0.05,-0.,-0.])-1/2*E([-0.1,-0.,-0.]))/.05**3

converged SCF energy = -93.1910718986852
converged SCF energy = -92.2872454018672
converged SCF energy = -90.4846658949383
converged SCF energy = -89.5859297811048


0.06758510915005898

In [26]:
(1/2*E([0.,0.1,0.])-E([0.,0.05,0.])+E([-0.,-0.05,-0.])-1/2*E([-0.,-0.1,-0.]))/.05**3

converged SCF energy = -92.8356540066697
converged SCF energy = -92.1096806157203
converged SCF energy = -90.6619546436914
converged SCF energy = -89.9402449006837


0.17135228756615103

In [36]:
(H([0.05,0,0])-H([-0.05,0,0]))/.1

converged SCF energy = -92.2872454018672
converged SCF energy = -90.4846658949384


array([[ 0.06751124,  0.01498405,  0.00056537],
       [ 0.01498405, -0.00714033,  0.00846957],
       [ 0.00056537,  0.00846957, -0.01068789]])

In [38]:
(H([0,0.05,0])-H([0,-0.05,0]))/.1

converged SCF energy = -92.1096806157204
converged SCF energy = -90.6619546436914


array([[ 0.01498673, -0.0071517 ,  0.00847199],
       [-0.0071517 ,  0.17119461, -0.0521323 ],
       [ 0.00847199, -0.0521323 , -0.01419098]])

In [39]:
(H([0,0,0.05])-H([0,0,-0.05]))/.1

converged SCF energy = -91.4195458735324
converged SCF energy = -91.3517977452635


array([[ 0.00057596,  0.00846519, -0.01068783],
       [ 0.00846519, -0.05211516, -0.01416793],
       [-0.01068783, -0.01416793,  0.03845216]])

In [37]:
ch

array([[[-0.06736416, -0.01498935, -0.00057113],
        [-0.01498935,  0.0071365 , -0.00846982],
        [-0.00057113, -0.00846982,  0.01068536]],

       [[-0.01498935,  0.0071365 , -0.00846982],
        [ 0.0071365 , -0.17087998,  0.0521149 ],
        [-0.00846982,  0.0521149 ,  0.01418075]],

       [[-0.00057113, -0.00846982,  0.01068536],
        [-0.00846982,  0.0521149 ,  0.01418075],
        [ 0.01068536,  0.01418075, -0.03847488]]])