In [3]:
from pyscf import scf,gto
from pyscf.geomopt.berny_solver import optimize
import basis_set_exchange as bse
import numpy as np

In [4]:
pcxbs={"H":"pc-2",'C':bse.get_basis("pcX-2",fmt="nwchem",elements=[6]),'N':bse.get_basis("pcX-2",fmt="nwchem",elements=[7])\
      ,'O':bse.get_basis("pcX-2",fmt="nwchem",elements=[8]),'F':bse.get_basis("pcX-2",fmt="nwchem",elements=[9])}

In [5]:
CH4=gto.M(atom="C 0 0 0; H 2.04 0 -.1; H .5 1.5 -.1; H .5 -1.5 -.1; H 0 0 2.04",unit="Bohr",basis=pcxbs,verbose=0)
NH3=gto.M(atom="N 0 0 0; H 2 0 0; H .5 1.5 0; H .5 -1.5 .2",unit="Bohr",basis=pcxbs,verbose=0)
H2O=gto.M(atom="O 0 0 0; H 2 0 0; H .5 1.5 0",unit="Bohr",basis=pcxbs,verbose=0)
HF=gto.M(atom="F 0 0 0; H 2 0 0",unit="Bohr",basis=pcxbs,verbose=0)

In [6]:
CH4scf=scf.RHF(CH4)
NH3scf=scf.RHF(NH3)
H2Oscf=scf.RHF(H2O)
HFscf=scf.RHF(HF)

In [37]:
 conv_params = {  
            'gradientmax': 0.45e-5,  # Eh/[Bohr|rad]
            'gradientrms': 0.15e-5,  # Eh/[Bohr|rad]
            'stepmax': 1.8e-4,       # [Bohr|rad]
            'steprms': 1.2e-4,       # [Bohr|rad]
        }

In [38]:
CH4opt=optimize(CH4scf,**conv_params)
NH3opt=optimize(NH3scf,**conv_params)
H2Oopt=optimize(H2Oscf,**conv_params)
HFopt=optimize(HFscf,**conv_params)

In [39]:
optgs=((CH4opt.atom_coords()-CH4opt.atom_coords()[0],NH3opt.atom_coords()-NH3opt.atom_coords()[0],H2Oopt.atom_coords()-H2Oopt.atom_coords()[0],HFopt.atom_coords()-HFopt.atom_coords()[0]))

In [40]:
np.save("optgeoms",optgs)

In [41]:
np.load("optgeoms.npy",allow_pickle=True)

array([array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
              [ 2.04365216e+00, -4.12864839e-12,  2.88325321e-02],
              [-6.67626958e-01,  1.66880131e+00, -9.72999663e-01],
              [-6.67626958e-01, -1.66880131e+00, -9.72999663e-01],
              [-7.08402540e-01,  2.18753828e-11,  1.91716013e+00]]),
       array([[ 0.        ,  0.        ,  0.        ],
              [ 1.86654855, -0.01597262, -0.26632433],
              [-0.45212441,  1.58915037,  0.90850058],
              [-0.45006859, -1.45943576,  1.10574591]]),
       array([[ 0.        ,  0.        ,  0.        ],
              [ 1.73352672, -0.38419879,  0.        ],
              [-0.12082414,  1.77147401,  0.        ]]),
       array([[0.        , 0.        , 0.        ],
              [1.69573887, 0.        , 0.        ]])], dtype=object)

In [42]:
for j in optgs:
    for i in j:
        print(np.linalg.norm(i))

0.0
2.043855535391837
2.0438571177507976
2.0438571177510663
2.0438534958418515
0.0
1.8855204253782516
1.8855208041268563
1.885520752933187
0.0
1.775591054614095
1.775589655593952
0.0
1.6957388734575747
