# GPAW

In [110]:
from ase import Atoms
from ase.units import Bohr
from gpaw import GPAW
import numpy as np
import glob

import sys
sys.path.insert(0, '/home/misa/APDFT/prototyping/atomic_energies/')
import alchemy_tools as at

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
plt.rcParams['font.size'] = 20

In [13]:
basepath = '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/'
# cell parameters
boxsize = 10.0
d = 1.12
pos1 = [boxsize/2, boxsize/2, boxsize/2-d/2]
pos2 = [boxsize/2, boxsize/2, boxsize/2+d/2]
molecules = ['H2', 'He2', 'Li2', 'Be2', 'B2', 'C2', 'N2']

In [5]:
from gpaw import Mixer, MixerSum, MixerDif
from gpaw.eigensolvers import CG
for mol in molecules:
    molecule = Atoms(mol, positions=[pos1, pos2], cell=(boxsize, boxsize, boxsize), pbc=False)
#     calc = GPAW(mode='fd', h = 0.1, xc='LDA', nbands=-8, mixer=Mixer(0.02, 5, 100))
    calc = GPAW(mode='fd', h = 0.1, xc='LDA', eigensolver=CG(niter=10, rtol=0.20), nbands=-10)
    molecule.set_calculator(calc)
    molecule.get_total_energy()
    n = calc.get_all_electron_density()
    ev = calc.get_eigenvalues()
    hl = calc.get_homo_lumo()
    occ = calc.get_occupation_numbers()
    
    np.save(basepath+mol+'_dens', n)
    np.savetxt(basepath+mol+'_ev', ev)
    np.savetxt(basepath+mol+'_hl', hl)
    np.savetxt(basepath+mol+'_occ', occ)
    


  ___ ___ ___ _ _ _  
 |   |   |_  | | | | 
 | | | | | . | | | | 
 |__ |  _|___|_____|  19.8.1
 |___|_|             

User:   misa@pc-avl24
Date:   Sat Feb 15 19:31:34 2020
Arch:   x86_64
Pid:    9650
Python: 3.7.3
gpaw:   /home/misa/anaconda3/envs/atomic-energies/lib/python3.7/site-packages/gpaw
_gpaw:  /home/misa/anaconda3/envs/atomic-energies/lib/python3.7/site-packages/
        _gpaw.cpython-37m-x86_64-linux-gnu.so
ase:    /home/misa/anaconda3/envs/atomic-energies/lib/python3.7/site-packages/ase (version 3.17.0)
numpy:  /home/misa/anaconda3/envs/atomic-energies/lib/python3.7/site-packages/numpy (version 1.16.4)
scipy:  /home/misa/anaconda3/envs/atomic-energies/lib/python3.7/site-packages/scipy (version 1.2.1)
libxc:  4.3.4
units:  Angstrom and eV
cores:  1

Input parameters:
  eigensolver: {name: cg,
                niter: 10}
  h: 0.1
  nbands: -10

System changes: positions, numbers, cell, pbc, initial_charges, initial_magmoms 

Initialize ...

B-setup:
  name: Boron
  id: 02e2e

iter:  48  19:35:12  +0.70  -0.49     1.474778    0      1      
iter:  49  19:35:16  -0.50  -0.67     1.735575    0      1      
iter:  50  19:35:20  +0.13  -0.77     1.375728    0      1      
iter:  51  19:35:24  -0.12  -0.44     1.322943    0      1      
iter:  52  19:35:28  -0.88  -0.44     1.701926    0      1      
iter:  53  19:35:32  +0.70  -0.48     1.466738    0      1      
iter:  54  19:35:36  -0.25  -0.67     1.735174    0      1      
iter:  55  19:35:40  +0.02  -0.77     1.371499    0      1      
iter:  56  19:35:45  +0.37  -0.44     1.326920    0      1      
iter:  57  19:35:49  -0.18  -0.44     1.733180    0      1      
iter:  58  19:35:53  +0.84  -0.49     0.701519    0      1      
iter:  59  19:35:57  +0.70  -0.51     1.557129    0      1      
iter:  60  19:36:01  +0.80  -0.68     1.216192    0      1      
iter:  61  19:36:06  -1.43  -0.43     1.148804    0      1      
iter:  62  19:36:10  +0.17  -0.42     1.740765    0      1      
iter:  63  19:36:14  +0.5

iter: 175  19:44:03  +0.40  -0.75     1.384894    0      1      
iter: 176  19:44:07  -1.05  -0.44     1.299467    0      1      
iter: 177  19:44:12  -0.33  -0.44     1.725858    0      1      
iter: 178  19:44:16  +0.64  -0.49     1.454389    0      1      
iter: 179  19:44:20  -0.03  -0.67     1.732371    0      1      
iter: 180  19:44:24  +0.17  -0.77     1.372765    0      1      
iter: 181  19:44:28  +0.08  -0.44     1.317491    0      1      
iter: 182  19:44:32  -0.42  -0.44     1.709675    0      1      
iter: 183  19:44:36  +0.60  -0.49     1.423132    0      1      
iter: 184  19:44:40  -0.18  -0.66     1.722697    0      1      
iter: 185  19:44:45  +0.02  -0.76     1.373500    0      1      
iter: 186  19:44:48  +0.13  -0.44     1.344500    0      1      
iter: 187  19:44:52  -0.34  -0.44     1.724054    0      1      
iter: 188  19:44:57  +0.34  -0.49     1.487108    0      1      
iter: 189  19:45:01  -0.79  -0.68     1.745130    0      1      
iter: 190  19:45:05  -0.2

iter: 302  19:53:05  -0.27  -0.44     1.708303    0      1      
iter: 303  19:53:09  +0.64  -0.48     1.468315    0      1      
iter: 304  19:53:13  -0.48  -0.67     1.735151    0      1      
iter: 305  19:53:18  -0.27  -0.77     1.357917    0      1      
iter: 306  19:53:22  -1.21  -0.44     1.350551    0      1      
iter: 307  19:53:26  -0.35  -0.44     1.682445    0      1      
iter: 308  19:53:30  +0.64  -0.48     1.470546    0      1      
iter: 309  19:53:35  -0.14  -0.67     1.736998    0      1      
iter: 310  19:53:40  -0.19  -0.77     1.380858    0      1      
iter: 311  19:53:45  +0.02  -0.44     1.355395    0      1      
iter: 312  19:53:50  -0.39  -0.44     1.721730    0      1      
iter: 313  19:53:54  +0.46  -0.49     1.473763    0      1      
iter: 314  19:53:58  -0.78  -0.67     1.736707    0      1      
iter: 315  19:54:03  -0.13  -0.77     1.400784    0      1      
iter: 316  19:54:08  -1.31  -0.44     1.356809    0      1      
iter: 317  19:54:13  -0.5

KeyboardInterrupt: 

In [ ]:
# single calculation

In [23]:
molecule = Atoms(molecules[1], positions=[pos1, pos2], cell=(boxsize, boxsize, boxsize), pbc=False)
calc = GPAW(mode='fd', h = 0.5, xc='LDA', txt='H2.txt', nbands=-4)
molecule.set_calculator(calc)
molecule.get_total_energy()

8.572582409307158

In [ ]:
# convert density from Angstrom to Bohr

In [86]:
dens_paths = glob.glob('/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/*_dens.npy')
dens_paths

['/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/Li2_dens.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/H2_dens.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/N2_dens.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/C2_dens.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/He2_dens.npy']

In [87]:
# scale by volume of grid point
dv_Bohr = (boxsize/Bohr)**3 / np.product(n.shape)
dv_Ang = boxsize**3/np.product(n.shape)

In [88]:
for p in dens_paths:
    n = np.load(p)
    dens_Bohr = ((n*Bohr**3)*dv_Bohr)
    np.save(p.split('.')[0]+'_bohr.'+p.split('.')[1], dens_Bohr)

In [90]:
dens_Bohr.shape

(200, 200, 200)

In [75]:
# atomic energies without electronic potential

In [91]:
dens_paths = glob.glob('/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/*_dens_bohr.npy')
dens_paths

['/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/He2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/C2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/Li2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/H2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/N2_dens_bohr.npy']

In [111]:
dens_paths = ['/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/H2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/He2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/Li2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/C2_dens_bohr.npy',
 '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/GPAW/N2_dens_bohr.npy']

In [112]:
densities = []
for p in dens_paths:
    densities.append(np.load(p))

In [114]:
densities.insert(0, np.zeros((200, 200, 200)))

In [116]:
len_gpt_1D = (boxsize/Bohr)/(dens.shape[0])
x_coords = np.linspace(len_gpt_1D/2, (boxsize/Bohr)-len_gpt_1D/2, dens.shape[0])
meshgrid = np.meshgrid(x_coords, x_coords, x_coords, indexing='ij')

In [117]:
lam_vals = [0.0, 1/7, 2/7, 3/7, 6/7, 7/7]
nuclei = np.array([[7, pos1[0], pos1[2], pos1[2]], [7, pos2[0], pos2[2], pos2[2]]])
nuclei

array([[7.  , 5.  , 4.44, 4.44],
       [7.  , 5.  , 5.56, 5.56]])

In [125]:
av_dens = at.integrate_lambda_density(densities, lam_vals)

In [126]:
at.calculate_atomic_energies(av_dens, nuclei, meshgrid)

(array([-5.80398923, -6.84037677]), array([-0.82914132, -0.97719668]))

In [124]:
densities[0].flatten()

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
n.shape[0]

In [ ]:
1/n.shape[0]**3*n.sum()*1000

In [ ]:
calc.get_eigenvalues()

In [ ]:
calc.get_homo_lumo()

In [ ]:
calc.get_occupation_numbers()

# VASP

In [ ]:
import sys
sys.path.insert(0, '/home/misa/APDFT/prototyping/atomic_energies/')

import alchemy_tools2 as at
import numpy as np
from explore_qml_data import get_free_atom_data

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
plt.rcParams['font.size'] = 20

In [ ]:
basepath = '/home/misa/APDFT/prototyping/atomic_energies/results/different_resevoir/'
subpath = ['H2', 'He2', 'Li2', 'Be2', 'B2', 'C2', 'N2']
paths = []
for sp in subpath:
    paths.append(basepath + sp + '/' + 'CHG')


# $\partial_{\lambda} E$

In [ ]:
densities, nuclei, gpts, h_matrix = at.load_vasp_dens(paths)

In [ ]:
lam_vals = np.array([0,1,2,3,4,5,6,7])/7

In [ ]:
nuclei, atomic_energies_with_repulsion, atomic_energies, alch_pots = at.atomic_energy_decomposition(lam_vals, densities, nuclei, gpts, h_matrix)

In [ ]:
dEdlam = []
for d in densities:
    aer, atomic_energies, alch_pots = at.calculate_atomic_energies(d, nuclei, gpts, h_matrix)
    dEdlam.append(atomic_energies[0])
dEdlam = np.array(dEdlam)

In [ ]:
# # without electronic potential
# fig, ax = plt.subplots(1,1)
# plt.plot(lam_vals, dEdlam, '-o')
# ax.set_xlabel(r'$\lambda$')
# ax.set_ylabel(r'$\partial_{\lambda} E$')

In [ ]:
e_lumo = {'non':0.0, 'H2':-1.2080, 'He2':-0.1406 , 'Li2':-3.2962, 'Be2': -4.4627, 'B2':-6.1195, 'C2':-7.9358, 'N2':-2.0942}
# e_homo = {'H2':-8.8894, 'He2':}

In [ ]:
dElam_epot = dEdlam.copy()
for i,k in enumerate(e_lumo):
    dElam_epot[i] += e_lumo[k]
    print(e_lumo[k])

In [ ]:
# without electronic potential
fig, ax = plt.subplots(1,1)
plt.plot(lam_vals, dEdlam, '-o', label='without electronic potential')
plt.plot(lam_vals, dElam_epot, '-o', label='with electronic potential')
ax.set_xlabel(r'$\lambda$')
ax.set_ylabel(r'$\partial_{\lambda} E$')
ax.legend()