In [10]:
import sys
sys.path.insert(0, '/home/misa/APDFT/prototyping/atomic_energies')

import alchemy_tools as at
from geometry_euston import abc_to_hmatrix, distance_pbc
from parse_cube_files import CUBE

import numpy as np

In [37]:
def distance_MIC(pos_nuc, meshgrid, h_matrix):
    """
    calculates the distance between the position of the nucleus and the nearest image of a gridpoint
    
    pos_nuc: position of nucleus
    meshgrid: meshgrid containing x,y,z components of every gridpoint
    h_matrix: needed for calculation of MIC distance
    """
    
    distance = np.zeros((meshgrid[0].shape))
    
    for idx0 in range(meshgrid[0].shape[0]):
        for idx1 in range(meshgrid[0].shape[1]):
            for idx2 in range(meshgrid[0].shape[2]):
                distance[idx0][idx1][idx2] = distance_pbc(pos_nuc, np.array([meshgrid[0][idx0][idx1][idx2], meshgrid[1][idx0][idx1][idx2], meshgrid[2][idx0][idx1][idx2]]), h_matrix)
    
    return(distance)

In [ ]:
def distance_MIC2(pos_nuc, meshgrid, h_matrix):
    """
    calculates the distance between the position of the nucleus and the nearest image of a gridpoint
    
    pos_nuc: position of nucleus
    meshgrid: meshgrid containing x,y,z components of every gridpoint
    h_matrix: needed for calculation of MIC distance
    """
    
    hinv = np.linalg.inv(h_matrix)
    a_t = np.dot(hinv, a)
    
#     b_t = np.dot(hinv, b)
    b_t_x = hinv[0]*meshgrid[0]+hinv[1]*meshgrid[1]+hinv[2]*meshgrid[2]
    
    
    distance = np.zeros((meshgrid[0].shape))
    
    distance[idx0][idx1][idx2] = distance_pbc(pos_nuc, np.array([meshgrid[0][idx0][idx1][idx2], meshgrid[1][idx0][idx1][idx2], meshgrid[2][idx0][idx1][idx2]]), h_matrix)
    
    return(distance)

In [51]:
hinv[2]

array([0.        , 0.        , 0.02645882])

In [46]:
hinv = np.linalg.inv(h_matrix)
a = cube.atoms[0][1:4]
a_t = np.dot(hinv, a)

In [47]:
a_t

array([0.52863484, 0.60285443, 0.50028497])

In [8]:
cube = CUBE('/home/misa/APDFT/prototyping/atomic_energies/results/slice_ve38/dsgdb9nsd_001212/cube-files/ve_04.cube')

In [16]:
meshgrid = cube.get_grid()
distance_MIC()

In [21]:
cube.atoms[0][1:4]

array([19.979529, 22.784627])

In [26]:
# abc_to_hmatrix(20, 20, 20, 90, 90, 90)
h_matrix = np.array([cube.X*cube.NX, cube.Y*cube.NY, cube.Z*cube.NZ])
h_matrix

array([[37.794575,  0.      ,  0.      ],
       [ 0.      , 37.794575,  0.      ],
       [ 0.      ,  0.      , 37.794575]])

In [38]:
distances_mic = distance_MIC(cube.atoms[0][1:4], meshgrid, h_matrix)

In [39]:
distances_mic.shape

(175, 175, 175)

In [42]:
np.amax(distances_mic)

32.72340188943374

In [32]:
cube.atoms[0][1:4]

array([19.979529, 22.784627, 18.908058])

In [44]:
meshgrid_xyz = np.vstack([_.flatten() for _ in meshgrid]).T
dist_gpt_nuc = np.linalg.norm(meshgrid_xyz - cube.atoms[0][1:4], axis=1)

In [45]:
np.amax(dist_gpt_nuc)

35.7188390617939