In [1]:
import qml
import numpy as np

import sys
sys.path.insert(0, '/home/misa/APDFT/prototyping/atomic_energies/')
import alchemy_tools as alch
import qml_interface as qi

In [2]:
paths=qi.wrapper_alch_data()
# load data into list, count number of atoms per molecule
alchemy_data, molecule_size = qi.load_alchemy_data(paths)
local_reps = qi.generate_atomic_representations(alchemy_data, molecule_size)

local_labels = qi.generate_label_vector(alchemy_data, molecule_size.sum())

training_set_size = 100
global_idc = qi.get_indices(len(alchemy_data), training_set_size)
local_idc = qi.get_local_idx(global_idc[0], molecule_size), qi.get_local_idx(global_idc[1], molecule_size)


In [3]:
local_reps.shape

(7584, 210)

In [4]:
rep = local_reps[local_idc[0]], local_reps[local_idc[1]]
labels = local_labels[local_idc[0]], local_labels[local_idc[1]]
sigmas = np.logspace(-1, 4, 12) #14)
lams = np.logspace(-15, 0, 16)#16)

In [5]:
lams

array([1.e-15, 1.e-14, 1.e-13, 1.e-12, 1.e-11, 1.e-10, 1.e-09, 1.e-08,
       1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00])

In [6]:
out = qi.optimize_hypar(rep, labels, sigmas, lams)

In [7]:
t=out[0]

In [8]:
np.where(np.amin(t[:,2])==t)

(array([152]), array([2]))

In [9]:
np.amin(t[:,2])

0.13310842229486233

In [10]:
t[152]


array([1.23284674e+03, 1.00000000e-07, 1.33108422e-01])

In [12]:
out[2].mean()

0.13310842229486233