Goal of this notebook is to understand how to call cphf.solve_nos1(fvind, mo_energy, mo_occ, h1,max_cycle=20, tol=1e-9, hermi=False)  (better the shape of the arrays passed as arguments)

In [1]:
import pyscf
from pyscf import gto, scf
import numpy as np
import matplotlib.pyplot as plt
import inspect
#from pyscf.geomopt.berny_solver import optimize
#from pyscf.grad import rhf as grhf
#from pyscf.hessian import rhf as hrhf
from pyscf import lib
import inspect
from functools import reduce
from pyscf.scf import cphf
from pyscf.prop.polarizability.rhf import Polarizability
angstrom = 1 / 0.52917721067
#from pyscf.scf._response_functions import _gen_rhf_response 

In [2]:
def DeltaV(mol,dL):
    mol.set_rinv_orig_(mol.atom_coords()[0])
    dV=mol.intor('int1e_rinv')*dL[0]
    mol.set_rinv_orig_(mol.atom_coords()[1])
    dV+=mol.intor('int1e_rinv')*dL[1]
    return -dV.reshape((1,dV.shape[0],dV.shape[1]))

def fc(calc,deltaZ):
    mf = pyscf.qmmm.mm_charge(calc, calc.mol.atom_coords(), deltaZ)  # now is add_mm_charge
    class NoSelfQMMM(mf.__class__):
        def energy_nuc(self):
            q = self.mol.atom_charges().astype(np.float).copy()
            q1 =q+ np.asarray(deltaZ) 
            return self.mol.energy_nuc(q1)
    return(NoSelfQMMM(mf,mf.mm_mol))

In [19]:
import time
from functools import reduce
import numpy
from pyscf import lib
from pyscf.lib import logger
from pyscf.scf import cphf
from pyscf.prop.nmr import rhf as rhf_nmr
#from pyscf.scf import _gen_rhf_response

def dipole(mf):
    return mf.dip_moment(mf.mol, mf.make_rdm1())
def polarizability(polobj, with_cphf=True):
    log = logger.new_logger(polobj)
    mf = polobj._scf
    mol = mf.mol
    mo_energy = mf.mo_energy
    mo_coeff = mf.mo_coeff
    mo_occ = mf.mo_occ
    occidx = mo_occ > 0
    orbo = mo_coeff[:, occidx]
    orbv = mo_coeff[:,~occidx]

    charges = mol.atom_charges()
    coords  = mol.atom_coords()
    charge_center = numpy.einsum('i,ix->x', charges, coords) / charges.sum()
    int_r=DeltaV(mol,[.001,-.001])
    h1 = lib.einsum('xpq,pi,qj->xij', int_r, mo_coeff.conj(), orbo) #going to molecular orbitals?
    print(h1.shape, "shape (1, n ao, nocc)" )
    #print(mo_energy, mo_occ,h1)
    s1 = numpy.zeros_like(h1)
    vind = polobj.gen_vind(mf, mo_coeff, mo_occ)
    if with_cphf:
        mo1,e1 = cphf.solve(vind, mo_energy, mo_occ, h1, s1, polobj.max_cycle_cphf, polobj.conv_tol,verbose=log)
    else:
        mo1 = rhf_nmr._solve_mo1_uncoupled(mo_energy, mo_occ, h1, s1)[0]
    #e2 = numpy.einsum('xpi,ypi->xy', h1, mo1)
    # *-1 from the definition of dipole moment. *2 for double occupancy
    #e2 = (e2 + e2.T) * -2
    #return e2
    return mo1,e1

def gen_vind(self, mf, mo_coeff, mo_occ):  #polarizability
        '''Induced potential'''
        vresp = mf.gen_response(hermi=1)
        occidx = mo_occ > 0
        orbo = mo_coeff[:, occidx]
        nocc = orbo.shape[1]
        nao, nmo = mo_coeff.shape
        def vind(mo1):
            dm1 = lib.einsum('xai,pa,qi->xpq', mo1.reshape(-1,nmo,nocc), mo_coeff,orbo.conj())
            dm1 = (dm1 + dm1.transpose(0,2,1).conj()) * 2
            v1mo = lib.einsum('xpq,pi,qj->xij', vresp(dm1), mo_coeff.conj(), orbo)
            return v1mo.ravel()
        return vind
def hyper_polarizability(polobj, with_cphf=True):
    log = logger.new_logger(polobj)
    mf = polobj._scf
    mol = mf.mol
    mo_energy = mf.mo_energy
    mo_coeff = mf.mo_coeff
    mo_occ = mf.mo_occ
    occidx = mo_occ > 0
    orbo = mo_coeff[:, occidx]
    #orbv = mo_coeff[:,~occidx]

    charges = mol.atom_charges()
    coords  = mol.atom_coords()
    charge_center = numpy.einsum('i,ix->x', charges, coords) / charges.sum()
    int_r=DeltaV(mol,[.001,-.001])
    h1 = lib.einsum('xpq,pi,qj->xij', int_r, mo_coeff.conj(), orbo)
    s1 = numpy.zeros_like(h1)
    vind = polobj.gen_vind(mf, mo_coeff, mo_occ) #funct DM-> G(DM)
    if with_cphf:
        mo1, e1 = cphf.solve(vind, mo_energy, mo_occ, h1, s1,  polobj.max_cycle_cphf, polobj.conv_tol, verbose=log)
    else:
        mo1, e1 = rhf_nmr._solve_mo1_uncoupled(mo_energy, mo_occ, h1, s1)
    mo1 = lib.einsum('xqi,pq->xpi', mo1, mo_coeff)

    dm1 = lib.einsum('xpi,qi->xpq', mo1, orbo) * 2
    dm1 = dm1 + dm1.transpose(0,2,1)
    vresp = mf.gen_response(hermi=1) # (J-K/2)(dm)
    h1ao = int_r + vresp(dm1) #Fock matrix
    # *2 for double occupancy
    e3  = lib.einsum('xpq,ypi,zqi->xyz', h1ao, mo1, mo1) * 2
    e3 -= lib.einsum('pq,xpi,yqj,zij->xyz', mf.get_ovlp(), mo1, mo1, e1) * 2
    e3 = (e3 + e3.transpose(1,2,0) + e3.transpose(2,0,1) +
          e3.transpose(0,2,1) + e3.transpose(1,0,2) + e3.transpose(2,1,0))
    e3 = -e3
    log.debug('Static hyper polarizability tensor\n%s', e3)
    return e3

In [24]:
mol = gto.Mole(atom='H 0 0 0; H 0 0 1.2', unit="Bohr",basis="STO-3G")
mol=gto.Mole(atom="C 0 0 0 ;O 0 0 2.", unit="Bohr", basis= "3-21G")
mf = scf.RHF(mol)
e=mf.scf()
O=np.diag(mf.mo_occ)

Initialize <pyscf.gto.mole.Mole object at 0x7efff472be90> in <pyscf.scf.hf.RHF object at 0x7effc8a83a10>


converged SCF energy = -112.078731735791


In [25]:
plo=Polarizability(mf) #polariz obj

In [26]:
pa,e1=polarizability(plo)

(1, 18, 7) shape (1, n ao, nocc)


In [29]:
np.round(e1,decimals=4)

array([[[ 0.0056, -0.    , -0.0009, -0.0005, -0.    ,  0.    ,  0.0001],
        [-0.    , -0.0043,  0.0004, -0.0004, -0.    ,  0.    ,  0.0005],
        [-0.0009,  0.0004,  0.0001,  0.0002,  0.    , -0.    , -0.0001],
        [-0.0005, -0.0004,  0.0002,  0.0001,  0.    , -0.    ,  0.0001],
        [-0.    , -0.    ,  0.    ,  0.    ,  0.0001,  0.    ,  0.    ],
        [ 0.    ,  0.    , -0.    , -0.    ,  0.    ,  0.0001,  0.    ],
        [ 0.0001,  0.0005, -0.0001,  0.0001,  0.    ,  0.    , -0.0002]]])

In [7]:
pa

array([[[0.        ],
        [0.00057807]]])

In [8]:
hf1=fc(mf,[.001,-0.001])
hf1.scf()

converged SCF energy = -1.1103355584584


-1.1103355584583992

In [9]:
C1= hf1.mo_coeff
C1

array([[ 0.53859761, -1.35712572],
       [ 0.53702883,  1.35774726]])

In [10]:
C=np.flip(mf.mo_coeff.copy(),axis=0)

In [11]:
C

array([[ 0.53781331, -1.35743672],
       [ 0.53781331,  1.35743672]])

In [12]:
C1-C

array([[ 0.0007843 ,  0.000311  ],
       [-0.00078448,  0.00031055]])

In [13]:
nao=mol.nao
nocc=mol.nelectron//2 #RHF
U=np.zeros((nao,nao))
U[:,:nocc]=pa[0,:,:nocc]
U=U.T-U
C@U

array([[ 0.0007847,  0.0003109],
       [-0.0007847,  0.0003109]])

In [14]:
mo1=lib.einsum('xqi,pq->xpi', pa, mf.mo_coeff)
dm1 = lib.einsum('xpi,qi->xpq', mo1, mf.mo_coeff[:,mf.mo_occ > 0]) * 2
dm1 = dm1 + dm1.transpose(0,2,1)
dm1

array([[[ 0.00168808,  0.        ],
        [ 0.        , -0.00168808]]])

In [15]:
C@(U@O-O@U)@C.T

array([[ 0.00168808,  0.        ],
       [ 0.        , -0.00168808]])

In [16]:
C@U-(C1-C)

array([[ 3.96287780e-07, -1.05195689e-07],
       [-2.16707694e-07,  3.48063087e-07]])

In [17]:
C+C@U,C1

(array([[ 0.53859801, -1.35712582],
        [ 0.53702861,  1.35774761]]),
 array([[ 0.53859761, -1.35712572],
        [ 0.53702883,  1.35774726]]))

In [18]:
inspect.getsource(mf.gen_response(hermi=1))

'            def vind(dm1):\n                vj, vk = mf.get_jk(mol, dm1, hermi=hermi)\n                return vj - .5 * vk\n'